### ISSUE TITLE
Fatal Exception OSH_LocationHandler when using building Release (NO SUCH  SERVICE)

### ISSUE THREAD

**Issue by samuk190** [OneSignal/react-native-onesignal#1023]
**Description:**
When I do react-run android --variant release
it install my react native app release version, ok.. but after I log in in my app (it calls subscribe after logging) it works ok. When I put the app on the background and open again I get this error and it closes .

It doesnt open until I erase all data and log-in again.

I dont have this issue on debug version

```

FATAL EXCEPTION: OSH_LocationHandlerThread
Process: com.modulo10, PID: 17869
java.lang.IllegalArgumentException: No such service ComponentInfo{com.modulo10/com.onesignal.SyncJobService}
	at android.os.Parcel.readException(Parcel.java)
	at android.os.Parcel.readException(Parcel.java)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java)
	at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:155)
	at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:124)
	at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:69)
	at com.onesignal.LocationController.scheduleUpdate(LocationController.java:109)
	at com.onesignal.LocationController.fireCompleteForLocation(LocationController.java:353)
	at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnected(GMSLocationController.java:134)
	at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source)
	at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source)
	at com.google.android.gms.common.api.internal.zaak.zaaq(Unknown Source)
	at com.google.android.gms.common.api.internal.zaak.onConnected(Unknown Source)
	at com.google.android.gms.common.api.internal.zabe.onConnected(Unknown Source)
	at com.google.android.gms.common.api.internal.zaq.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.zaf.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source)
	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source)
	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source)
	at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java)
	at com.google.android.gms.internal.common.zze.dispatchMessage(Unknown Source)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java)

```

**Environment**

**Steps to Reproduce Issue:**

I'm doing oneSignal init in my index.js 
1. react run-android --variant release
2. do something in my app, then go to background
3. Crash

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by samuk190** [comment]
rebuild entire android/ios 

it worked.
