### ISSUE TITLE
postNotification() doesn't work on Android

### ISSUE THREAD

**Issue by Valegox** [OneSignal/react-native-onesignal#1055]
**Description:**

`OneSignal.postNotification()` doesn't work on Android.

**Environment**

Version of the OneSignal React-Native SDK: `3.9.1`.
SDK added with `yarn add react-native-onesignal`.

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project,
1. Follow the [setup](https://documentation.onesignal.com/docs/react-native-sdk-setup) and initialize OneSignal in your main component,
1. Use `postNotification()` as mentioned [here](https://documentation.onesignal.com/docs/sdk-reference#sending-notifications) (for example on press on a button),
1. `npx react-native run-android`.

**Anything else:**

There aren't any error message. When I send a notification from the OneSignal panel or from an iOS device, it works regardless of the receiver's OS.

**Comment by rgomezp** [comment]
Howdy,
I tried reproducing this and actually I did get an error. It looks like the documentation is probably not up to date either. It isn't clear whether the arguments passed should be objects, arrays, etc.. We will investigate this and potentially put out a fix as well as try to clarify the docs.

In the meantime, can you please include a code-snippet of how you are actually calling the function?

Cheers

---
Trying to reproduce this issue uncovered an issue that I have opened with React Native [directly](https://github.com/facebook/react-native/issues/30178)

**Comment by Valegox** [comment]
Thanks for your quick answer. Here is the content of my `App.js`:

```
  constructor() {
        super()
        //Remove this method to stop OneSignal Debugging 
        OneSignal.setLogLevel(6, 0)

        OneSignal.init(
            "my-app-id", 
            {kOSSettingsKeyAutoPrompt : false, kOSSettingsKeyInAppLaunchURL: false, kOSSettingsKeyInFocusDisplayOption:2}
        )
        // Controls what should happen if a notification is received while the app is open. 2 means that the notification will go directly to the device's notification center.
        OneSignal.inFocusDisplaying(2)
    }

    componentDidMount() {
        //LOAD ONESIGNAL ID ON DEVICE
        OneSignal.getPermissionSubscriptionState( status => {
            deviceID = status.userId
        })
    }

    _sendNotification(ID, message) {
        let contents = {
            'en': message
        }
        console.log('sending', message, 'to', ID)
        OneSignal.postNotification(contents, {}, null, {include_player_ids:[ID]})
    }

    render() {
        return (
            <View style={styles.mainContainer}>
                <StatusBar barStyle="dark-content" />
                <SafeAreaView>
                    <ScrollView
                        contentInsetAdjustmentBehavior="automatic"
                        style={styles.scrollView}
                        contentContainerStyle={styles.scrollViewContent}
                    >
                        <Button title='SEND NOTIFICATION' onPress={ () => this._sendNotification(deviceID, "Hello world") } />
                    </ScrollView>
                </SafeAreaView>
            </View>
        )
    }
```

**Comment by rares-lupascu** [comment]
just to make sure u did it ... "my-app-id" u replaced this with ur actual app id from onesignal, right?

**Comment by rares-lupascu** [comment]
they also recommend getting the device in a different way btw
```
OneSignal.addEventListener('ids', this.onIds);
onIds(device) {
    console.log('Device info: ', device);
}
```
[https://documentation.onesignal.com/docs/react-native-sdk-setup](https://documentation.onesignal.com/docs/react-native-sdk-setup) (all the way at the bottom)

**Comment by Valegox** [comment]
> just to make sure u did it ... "my-app-id" u replaced this with ur actual app id from onesignal, right?

Haha, don't worry I put my real app id



> they also recommend getting the device in a different way btw
> 
> ```
> OneSignal.addEventListener('ids', this.onIds);
> onIds(device) {
>     console.log('Device info: ', device);
> }
> ```
> 
> https://documentation.onesignal.com/docs/react-native-sdk-setup (all the way at the bottom)

Thanks for your help, fortunately I found a way to do not send notifications from android devices (a solution specific to my project). I let this issue opened.

**Comment by rgomezp** [comment]
Howdy,
I can confirm that this is an issue. Looking at the Android logs, the error is this:

```
2020-10-26 18:17:47.773 28811-29594/com.rnonesignal W/System.err: org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONArray
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:98)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at org.json.JSONArray.<init>(JSONArray.java:110)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.geektime.rnonesignalandroid.RNOneSignal.postNotification(RNOneSignal.java:338)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
2020-10-26 18:17:47.774 28811-29594/com.rnonesignal W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

However, this doesn't cause the application to crash or any visible errors on the JS/React side of things.

It looks like a [fix was made](https://github.com/OneSignal/react-native-onesignal/commit/6bfec303a838c7251669a118848ccc9581487931) for a related but separate issue that is causing this new problem.

**My testing code snippet:**
```js
const { userId } = await OneSignal.getDeviceState();   // this func is only available in the major release beta
OneSignal.postNotification({"en": "Hello! Howdy"}, {}, null, {include_player_ids:[userId]});
```

Reverting that commit, it looks like the same code would lead to this exception after a fresh app start:

```
2020-10-26 18:23:25.670 29578-30651/com.rnonesignal E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:101)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:72)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:68)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
```

However, reloading the app in dev mode leads to no exception.

Thanks for pointing out this issue. We will try to get this resolved as soon as we can. 

If anyone can help with this one it would be greatly appreciated and should be fairly straight forward.

Thanks for your patience.

**Comment by rgomezp** [comment]
Opened PR #1072 to address this. It will be part of the major release which is currently in Beta
