### ISSUE TITLE
WorkManager is not initialized properly 

### ISSUE THREAD

**Issue by IsmetGlumcevic** [OneSignal/react-native-onesignal#1285]
I run my old app on macbook m1 targeting android 12 and get error. 
rn 0.64
react-native-onesignal": "^4.1.1 (npm installl)

log:
```
promptForPushNotificationsWithUserResponse: this function is not supported on Android
```

android studio logcat:
```java
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
        at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
        at androidx.work.WorkManager.getInstance(WorkManager.java:184)
        at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager.java:48)
        at com.onesignal.OneSignal.handleActivityLifecycleHandler(OneSignal.java:900)
        at com.onesignal.OneSignal.init(OneSignal.java:782)
        at com.onesignal.OneSignal.setAppId(OneSignal.java:683)
        at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1096)
        at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:819)
        at com.onesignal.OneSignal$5.complete(OneSignal.java:1037)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
```
AndroidManifest.xml:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.xxx"
  xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      tools:node="replace"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <!-- Change the value to true to enable pop-up for in foreground on receiving remote notifications (for prevent duplicating while showing local notifications set this to false) -->
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="false"/>
      <!-- Change the resource name to your App's accent color - or any other color you want -->
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" 
                android:exported="true">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>

      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="true">
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"
        android:launchMode="singleTask"
        android:exported="true">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="xxx" />
        </intent-filter>
      </activity>
    </application>
</manifest>
```
setup function:
```javascript
     async function setupOnesignal() {
      OneSignal.setLogLevel(6, 0);
      OneSignal.setAppId('c9d0da18-8945-4857-aab4-97047cc57128');

     OneSignal.promptForPushNotificationsWithUserResponse(response => {
       console.log('Prompt response:', response);
     });
    OneSignal.setNotificationWillShowInForegroundHandler(
      notificationReceivedEvent => {
        console.log(
          'OneSignal: notification will show in foreground:',
          notificationReceivedEvent,
         );
        let notification = notificationReceivedEvent.getNotification();
        const data = notification.additionalData;
        const button1 = {
          text: 'Cancel',
          onPress: () => {
            notificationReceivedEvent.complete();
          },
          style: 'cancel',
        };
        const button2 = {
          text: 'Complete',
          onPress: () => {
            notificationReceivedEvent.complete(notification);
          },
        };
        Alert.alert('Complete notification?', 'Test', [button1, button2], {
          cancelable: true,
        });
      },
    );
    const deviceState = await OneSignal.getDeviceState();
    setIsSubscribed(deviceState.isSubscribed);
    }

    useEffect(() => {
     setupOnesignal();
    }, []);
```

**Comment by rgomezp** [comment]
Howdy Ismet,
>promptForPushNotificationsWithUserResponse: this function is not supported on Android

This is expected on Android devices as it is not supported.

For the WorkManager issue, it seems like a totally separate problem for you. When is this occurring? Is it right when you open the app? Does the app crash? What is the behavior you are seeing?

**Comment by IsmetGlumcevic** [comment]
Hi, yes its happen when I open the app and app crash in production, in dev sometimes crash.

**Comment by IsmetGlumcevic** [comment]
react-native info:
System:
OS: macOS 11.6
CPU: (8) arm64 Apple M1
Memory: 116.09 MB / 8.00 GB
Shell: 5.8 - /bin/zsh
Binaries:
Node: 16.9.1 - /usr/local/bin/node
Yarn: Not Found
npm: 7.21.1 - /opt/homebrew/bin/npm
Watchman: 2021.08.30.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.0 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
Android SDK:
API Levels: 28, 29, 30, 31
Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
System Images: android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
Android NDK: Not Found
IDEs:
Android Studio: 2020.3 AI-203.7717.56.2031.7678000
Xcode: 13.0/13A233 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_292 - /usr/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 17.0.1 => 17.0.1
react-native: 0.64.0 => 0.64.0

android/build.gradle
 
     buildscript {
     ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "21.1.0" // default: "+"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        androidXCore = "1.0.2"
       }
      repositories {
        google()
        jcenter()
     }
       dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
     }
    }

**Comment by IsmetGlumcevic** [comment]
whether I was the only one to get this bug?

**Comment by AhmetMelihSerter** [comment]
https://github.com/OneSignal/react-native-onesignal/issues/1152#issuecomment-769346899 it's work me. @IsmetGlumcevic

**Comment by rgomezp** [comment]
Closing due to no response to the above suggestion

**Comment by nan-li** [comment]
Hi @IsmetGlumcevic,

Thank you for reporting this many months ago. We are investigating this issue of `WorkManager is not initialized properly` and I want to check in if you are still seeing this crash?
