### ISSUE TITLE
No feedback when sending notification from OneSignal dashboard

### ISSUE THREAD

**Issue by sweatherall** [OneSignal/react-native-onesignal#1329]
**Description:**
I wish I had a specific error to post, but I don't because the issue is that I am getting no feedback/logs when I push a notification from the OneSignal dashboard UI. Through the logcats I can see that OneSignal is getting initialized and it is finding my custom `NotificationServiceExtension` class. But upon sending a notification from the dashboard (I tried with the app in foreground as well as background) there is nothing I see to determine what is going wrong, and I do not receive any notifications on device. I'm wondering how I can debug this or what to look for, or if you spot anything off in the code below.

**Environment**
RN: 0.66.3
react-native-onesignal: 4.3.3
installed via npm
Implementing background notification functionality for Android device, following [these instructions](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension).

**Steps to Reproduce Issue:**
  1. Install the OneSignal SDK using npm into your project
  2. Setup the [Android Notification Service Extension](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension)
  3. Attempt to receive a push notification from the dashboard UI

**Logcats on startup and during 'sending a notification from the OneSignal dashboard':**
```
2021-11-23 17:00:35.098 I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app ONESIGNAL_SDK_FCM_APP_NAME
2021-11-23 17:00:38.910 I/ReactNativeJS: 'setEventHandler!!!', 'OneSignal-notificationWillShowInForeground'
2021-11-23 17:00:40.163 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: true jsonBody: {"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":false,"loc_time_stamp":1637704829321,"app_id":"619bb485-4121-436c-97e2-660b16a18edd"}
2021-11-23 17:00:40.165 D/OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_session
2021-11-23 17:00:40.167 D/OneSignal: OneSignalRestClient: POST SEND JSON: {"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":false,"loc_time_stamp":1637704829321,"app_id":"619bb485-4121-436c-97e2-660b16a18edd"}
2021-11-23 17:00:40.261 V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_session
2021-11-23 17:00:40.262 D/OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_session
2021-11-23 17:00:40.266 D/OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"6f107fca-b907-4a0a-b088-b6b6d55912fa"}
2021-11-23 17:00:40.268 D/OneSignal: doCreateOrNewSession:response: {"success":true,"id":"6f107fca-b907-4a0a-b088-b6b6d55912fa"}
2021-11-23 17:00:40.271 I/OneSignal: Device registered, UserId = 6f107fca-b907-4a0a-b088-b6b6d55912fa
2021-11-23 17:00:45.272 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
2021-11-23 17:00:47.166 I/OneSignal: Restoring notifications
2021-11-23 17:00:47.167 I/OneSignal: Querying DB for notifications to restore: created_time > 1637100047 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1637704847
2021-11-23 17:00:47.178 I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=f33c5c38-e3bf-439b-b0e5-2282190a0d0d, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]
2021-11-23 17:01:20.626 D/OneSignal: ActivityLifecycleHandler runLostFocusLogic
2021-11-23 17:01:20.626 D/OneSignal: OSBackground sync, calling initWithContext
2021-11-23 17:01:20.628 V/OneSignal: initWithContext called with: com.onesignal.FocusDelaySyncJobService@9f8d591
2021-11-23 17:01:20.628 V/OneSignal: Starting OneSignal initialization!
2021-11-23 17:01:20.628 V/OneSignal: Found class: com.truckmap.truckmap.NotificationServiceExtension, attempting to call constructor
2021-11-23 17:01:20.628 D/OneSignal: OneSignal SDK initialization already completed.
2021-11-23 17:01:20.629 D/OneSignal: ActivityLifecycleHandler running AppFocusRunnable
2021-11-23 17:01:20.629 D/OneSignal: Application lost focus initDone: true
2021-11-23 17:01:20.629 D/OneSignal: Last session time set to: 1637704880629
2021-11-23 17:01:20.631 D/OneSignal: GMSLocationController onFocusChange!
2021-11-23 17:01:20.632 D/OneSignal: GMSLocationController GoogleApiClient requestLocationUpdates!
2021-11-23 17:01:20.633 W/OneSignal: FusedLocationApi.requestLocationUpdates failed!
    java.lang.NullPointerException: Calling thread must be a prepared Looper thread.
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:11)
        at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source:6)
        at com.onesignal.GMSLocationController$FusedLocationApiWrapper.requestLocationUpdates(GMSLocationController.java:198)
        at com.onesignal.GMSLocationController$LocationUpdateListener.init(GMSLocationController.java:181)
        at com.onesignal.GMSLocationController$LocationUpdateListener.<init>(GMSLocationController.java:165)
        at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:117)
        at com.onesignal.LocationController.onFocusChange(LocationController.java:326)
        at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1307)
        at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:279)
        at java.lang.Thread.run(Thread.java:920)
2021-11-23 17:01:20.633 D/OneSignal: Application backgrounded focus time: 121276294
2021-11-23 17:01:20.633 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 60
2021-11-23 17:01:20.633 D/OneSignal: FocusTimeProcessorUnattributed:sendUnsentTimeNow with time: 60 and influences: []
2021-11-23 17:01:20.633 D/OneSignal: FocusTimeProcessorUnattributed sendTime with: BACKGROUND
2021-11-23 17:01:20.634 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 60
2021-11-23 17:01:20.634 V/OneSignal: OSSyncService scheduleSyncTask:SYNC_AFTER_BG_DELAY_MS: 30000
2021-11-23 17:01:20.634 V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:atTime: 30000
2021-11-23 17:01:20.637 I/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:result: 1
2021-11-23 17:01:20.639 D/OneSignal: OneSignal scheduleSyncService unsyncedChanges: false
2021-11-23 17:01:20.640 D/OneSignal: LocationController scheduleUpdate lastTime: 45528 minTime: 600000
2021-11-23 17:01:20.640 V/OneSignal: OSSyncService scheduleLocationUpdateTask:delayMs: 554472
2021-11-23 17:01:20.640 V/OneSignal: OSSyncService scheduleSyncTask already update scheduled nextScheduledSyncTimeMs: 1637704910637
2021-11-23 17:01:20.640 D/OneSignal: OneSignal scheduleSyncService locationScheduled: true
2021-11-23 17:01:54.622 D/OneSignal: OSBackground sync, calling initWithContext
2021-11-23 17:01:54.623 V/OneSignal: initWithContext called with: com.onesignal.SyncJobService@5374282
2021-11-23 17:01:54.623 V/OneSignal: Starting OneSignal initialization!
2021-11-23 17:01:54.625 V/OneSignal: Found class: com.truckmap.truckmap.NotificationServiceExtension, attempting to call constructor
2021-11-23 17:01:54.625 D/OneSignal: OneSignal SDK initialization already completed.
2021-11-23 17:01:54.627 D/OneSignal: LocationController sendAndClearPromptHandlers from non prompt flow
2021-11-23 17:01:54.628 D/OneSignal: LocationController startGetLocation with lastLocation: Location[fused 39.142335,-86.544946 hAcc=9.648 et=+1d9h41m10s549ms alt=200.5009739730958 vAcc=3.0 vel=0.015822355 sAcc=0.10630146 bear=324.0258 {Bundle[EMPTY_PARCEL]}]
2021-11-23 17:01:54.635 D/OneSignal: LocationController fireCompleteForLocation with location: Location[fused 39.142335,-86.544946 hAcc=9.648 et=+1d9h41m10s549ms alt=200.5009739730958 vAcc=3.0 vel=0.015822355 sAcc=0.10630146 bear=324.0258 {Bundle[EMPTY_PARCEL]}]
2021-11-23 17:01:54.635 D/OneSignal: LocationController scheduleUpdate lastTime: 0 minTime: 600000
2021-11-23 17:01:54.635 V/OneSignal: OSSyncService scheduleLocationUpdateTask:delayMs: 600000
2021-11-23 17:01:54.635 V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:atTime: 600000
2021-11-23 17:01:54.637 V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob Scheduler already running!
2021-11-23 17:01:54.639 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
2021-11-23 17:01:54.640 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"app_id":"619bb485-4121-436c-97e2-660b16a18edd","device_os":"12","timezone":-18000,"timezone_id":"America\/New_York","language":"en","sdk":"040603","sdk_type":"react","android_package":"com.truckmap.truckmap.alpha","device_model":"Pixel 3","game_version":224,"net_type":0,"carrier":"Verizon","rooted":false,"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":true,"loc_time_stamp":1637704829321}
2021-11-23 17:01:54.641 I/OneSignal: Error updating the user record because of the null user id
2021-11-23 17:01:54.642 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"app_id":"619bb485-4121-436c-97e2-660b16a18edd","device_os":"12","timezone":-18000,"timezone_id":"America\/New_York","language":"en","sdk":"040603","sdk_type":"react","android_package":"com.truckmap.truckmap.alpha","device_model":"Pixel 3","game_version":224,"net_type":0,"carrier":"Verizon","rooted":false,"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":true,"loc_time_stamp":1637704829321}
2021-11-23 17:01:54.642 I/OneSignal: Error updating the user record because of the null user id
2021-11-23 17:01:54.643 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 60
2021-11-23 17:01:54.643 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 60
2021-11-23 17:01:54.643 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 60
2021-11-23 17:01:54.643 D/OneSignal: FocusTimeProcessorUnattributed:sendOnFocus with totalTimeActive: 60
2021-11-23 17:01:54.647 D/OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_focus
2021-11-23 17:01:54.655 D/OneSignal: OneSignalRestClient: POST SEND JSON: {"app_id":"619bb485-4121-436c-97e2-660b16a18edd","type":1,"state":"ping","active_time":60,"device_type":1,"net_type":0}
2021-11-23 17:01:54.774 V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_focus
2021-11-23 17:01:54.774 D/OneSignal: OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/6f107fca-b907-4a0a-b088-b6b6d55912fa/on_focus
2021-11-23 17:01:54.786 D/OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"id":"6f107fca-b907-4a0a-b088-b6b6d55912fa","success":true}
2021-11-23 17:01:54.787 D/OneSignal: FocusTimeProcessorUnattributed:saveUnsentActiveTime: 0
2021-11-23 17:01:54.787 D/OneSignal: LollipopSyncRunnable:JobFinished needsJobReschedule: true
2021-11-23 17:01:59.642 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
2021-11-23 17:02:28.553 D/OneSignal: OSBackground sync, calling initWithContext
2021-11-23 17:02:28.553 V/OneSignal: initWithContext called with: com.onesignal.SyncJobService@41b04ce
2021-11-23 17:02:28.553 V/OneSignal: Starting OneSignal initialization!
2021-11-23 17:02:28.553 V/OneSignal: Found class: com.truckmap.truckmap.NotificationServiceExtension, attempting to call constructor
2021-11-23 17:02:28.554 D/OneSignal: OneSignal SDK initialization already completed.
2021-11-23 17:02:28.554 D/OneSignal: LocationController sendAndClearPromptHandlers from non prompt flow
2021-11-23 17:02:28.555 D/OneSignal: LocationController startGetLocation with lastLocation: Location[fused 39.142335,-86.544946 hAcc=9.648 et=+1d9h41m10s549ms alt=200.5009739730958 vAcc=3.0 vel=0.015822355 sAcc=0.10630146 bear=324.0258 {Bundle[EMPTY_PARCEL]}]
2021-11-23 17:02:28.556 D/OneSignal: LocationController fireCompleteForLocation with location: Location[fused 39.142335,-86.544946 hAcc=9.648 et=+1d9h41m10s549ms alt=200.5009739730958 vAcc=3.0 vel=0.015822355 sAcc=0.10630146 bear=324.0258 {Bundle[EMPTY_PARCEL]}]
2021-11-23 17:02:28.557 D/OneSignal: LocationController scheduleUpdate lastTime: 0 minTime: 600000
2021-11-23 17:02:28.557 V/OneSignal: OSSyncService scheduleLocationUpdateTask:delayMs: 600000
2021-11-23 17:02:28.557 V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:atTime: 600000
2021-11-23 17:02:28.558 V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob Scheduler already running!
2021-11-23 17:02:28.560 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
2021-11-23 17:02:28.561 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"app_id":"619bb485-4121-436c-97e2-660b16a18edd","device_os":"12","timezone":-18000,"timezone_id":"America\/New_York","language":"en","sdk":"040603","sdk_type":"react","android_package":"com.truckmap.truckmap.alpha","device_model":"Pixel 3","game_version":224,"net_type":0,"carrier":"Verizon","rooted":false,"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":true,"loc_time_stamp":1637704829321}
2021-11-23 17:02:28.561 I/OneSignal: Error updating the user record because of the null user id
2021-11-23 17:02:28.561 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"app_id":"619bb485-4121-436c-97e2-660b16a18edd","device_os":"12","timezone":-18000,"timezone_id":"America\/New_York","language":"en","sdk":"040603","sdk_type":"react","android_package":"com.truckmap.truckmap.alpha","device_model":"Pixel 3","game_version":224,"net_type":0,"carrier":"Verizon","rooted":false,"loc_acc":9.648,"loc_type":1,"lat":39.1423346,"long":-86.5449463,"loc_bg":true,"loc_time_stamp":1637704829321}
2021-11-23 17:02:28.562 I/OneSignal: Error updating the user record because of the null user id
2021-11-23 17:02:28.562 D/OneSignal: FocusTimeProcessorUnattributed:getUnsentActiveTime: 0
2021-11-23 17:02:28.562 D/OneSignal: LollipopSyncRunnable:JobFinished needsJobReschedule: true
2021-11-23 17:02:33.564 D/OneSignal: UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
```

NotificationServiceExtension.java:
```
package com.truckmap.truckmap;

import android.content.Context;
import android.util.Log;
import org.json.JSONObject;

import com.onesignal.OSNotification;
import com.onesignal.OSMutableNotification;
import com.onesignal.OSNotificationReceivedEvent;
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler;

import java.math.BigInteger;
import android.graphics.Color;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;

@SuppressWarnings("unused")
public class NotificationServiceExtension implements OSRemoteNotificationReceivedHandler {

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {
        OSNotification notification = notificationReceivedEvent.getNotification();

        Log.i("OneSignalExample", "remoteNotificationReceived! " + notification);
        // Log.i("OneSignalExample", "Is app in focus? " + notificationReceivedEvent.getRawPayload().isAppInFocus);

        // Example of modifying the notification's accent color
        OSMutableNotification mutableNotification = notification.mutableCopy();
        mutableNotification.setExtender(builder -> {
            // Sets the accent color to Green on Android 5+ devices.
            // Accent color controls icon and action buttons on Android 5+. Accent color does not change app title on Android 10+
            builder.setColor(new BigInteger("FF00FF00", 16).intValue());
            // Sets the notification Title to Red
            Spannable spannableTitle = new SpannableString(notification.getTitle());
            spannableTitle.setSpan(new ForegroundColorSpan(Color.RED),0,notification.getTitle().length(),0);
            builder.setContentTitle(spannableTitle);
            // Sets the notification Body to Blue
            Spannable spannableBody = new SpannableString(notification.getBody());
            spannableBody.setSpan(new ForegroundColorSpan(Color.BLUE),0,notification.getBody().length(),0);
            builder.setContentText(spannableBody);
            //Force remove push from Notification Center after 30 seconds
            builder.setTimeoutAfter(30000);
            return builder;
        });
        JSONObject data = notification.getAdditionalData();
        Log.i("OneSignalExample", "Received Notification Data: " + data);

        // If complete isn't call within a time period of 25 seconds, OneSignal internal logic will show the original notification
        // To omit displaying a notification, pass `null` to complete()
        notificationReceivedEvent.complete(mutableNotification);
    }
}
```

AndroidManifest.xml:
```
<manifest android:targetSandboxVersion="1"
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.truckmap.truckmap"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/launcher"
        android:roundIcon="@mipmap/launcher_round"
        android:allowBackup="false"
        android:usesCleartextTraffic="true"
        android:theme="@style/AppTheme">

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/notification_icon" />

        <meta-data 
            android:name="com.onesignal.NotificationServiceExtension"
            android:value="com.truckmap.truckmap.NotificationServiceExtension" />

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:configChanges="keyboard|keyboardHidden|screenSize|smallestScreenSize|screenLayout|orientation|uiMode"
            android:windowSoftInputMode="adjustResize">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="geo" />
                <data android:scheme="truckmap" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="https"
                    android:host="truckmap.com"
                    android:pathPrefix="/place" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="https"
                    android:host="truckmap.com"
                    android:pathPrefix="/places" />
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:scheme="https"
                    android:host="truckmap.com"
                    android:pathPrefix="/route" />
            </intent-filter>
        </activity>

        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        <service android:name=".TruckMapService" />

    </application>

</manifest>
```

I would love to know how I can debug this, since there are no error logs anywhere I am at a loss.
Please let me know what other information I can provide.

Thank you!

**Comment by jkasten2** [comment]
@sweatherall It seems it isn't getting to your `remoteNotificationReceived` method as I don't see "Received Notification Data:" in your logcat.

Is the notification not displaying on the device at all? If not does fully removing `NotificationServiceExtension` help?

If that still does not work can you try a different device and / or Android emulator or different network?

**Comment by sweatherall** [comment]
@jkasten2 
> Is the notification not displaying on the device at all? 

It is not displaying on device at all

> does fully removing NotificationServiceExtension help?

The same behavior exists even if I remove the NotificationServiceExtension 🤔 

> can you try a different device and / or Android emulator or different network?

I can ask my coworker to try sometime next week. 
For what its worth, I was at one point receiving notifications on this same device and network. 

Since it's finding my `NotificationServiceExtension` class, but `remoteNotificationReceived` is not getting called, is the assumption that the dispatched event being sent from the OneSignal dashboard is not being received by my device possibly because of a network issue?

I appreciate your help!

**Comment by sweatherall** [comment]
@jkasten2 I had my coworker test today and they had the same experience as me - any suggestions on how to debug this?

**Comment by sweatherall** [comment]
Update: The issue was on our end and it was because we did not give OneSignal the correct app bundle ID for our 'alpha' build. We had it set up for our prod build, but we needed to create a new 'app' on the OneSignal dashboard specifically for our alpha build.
