### ISSUE TITLE
Argument 1 of OneSignal.sendOutcome must not be null

### ISSUE THREAD

**Issue by leethree** [OneSignal/react-native-onesignal#1348]
**Description:**

`sendOutcome` doesn't work without its 2nd argument since recent versions. it was working fine in previous versions.

**Environment**

react-native-onesignal v4.3.4
react-native: v0.66.4

**Steps to Reproduce Issue:**

1. `OneSignal.sendOutcome('foobar');`
2. see error:

![image](https://user-images.githubusercontent.com/648142/150323726-42a3b770-7b8d-469f-904c-2dbda3134aa9.png)

**Anything else:**

I think it's caused by this commit: https://github.com/OneSignal/react-native-onesignal/commit/7d48a4c39ee30bdb2d4e4711e992fb7d97a546bc

The default value of `handler` is removed:

![image](https://user-images.githubusercontent.com/648142/150324481-2f747000-8a33-4f3a-845d-3639a8ae97e7.png)

**Comment by nan-li** [comment]
Thanks for reporting @leethree, we will fix this in the next release.

In the meantime, as a temporary workaround, you can pass an empty function as the second argument.

**Comment by manuhook** [comment]
Hi @nan-li, on the last version I have this crash happening in production (never happen before):

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.OSOutcomeEventsController.sendSavedOutcomes()' on a null object reference
       at com.onesignal.OneSignal.init(OneSignal.java:837)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1136)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:844)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1077)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:292)
       at java.lang.Thread.run(Thread.java:929)
```

Do you think it's related ?
Thank you

**Comment by nan-li** [comment]
Hi @manuhook, I don't think your exception is related to the original poster's issue.

1. Are you on `react-native-onesignal v4.3.5`?
2. What devices and Android versions are experiencing this crash?
3. How many/percentage of users are being affected?

It looks like it may be related to [this open issue in the OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1514).
