### ISSUE TITLE
OneSignal AppId format is invalid.

### ISSUE THREAD

**Issue by arhmnsh** [OneSignal/react-native-onesignal#135]
I am getting this error while running Android app. Cannot receive any notifications.
iOS works fine though.

my build.gradle configs:
<img width="598" alt="screen shot 2017-01-09 at 9 09 39 am" src="https://cloud.githubusercontent.com/assets/1363724/21758321/903de394-d64b-11e6-873c-e794cd893bdf.png">

```
com.myapp E/OneSignal: OneSignal AppId format is invalid.
                       Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
                       
                       java.lang.NumberFormatException: Invalid long: "6373736aa256.9"
                           at java.lang.Long.invalidLong(Long.java:124)
                           at java.lang.Long.parse(Long.java:363)
                           at java.lang.Long.parsePositiveLong(Long.java:413)
                           at java.util.UUID.fromString(UUID.java:195)
                           at com.onesignal.OneSignal.init(OneSignal.java:222)
                           at com.onesignal.OneSignal.init(OneSignal.java:201)
                           at com.onesignal.OneSignal.access$000(OneSignal.java:69)
                           at com.onesignal.OneSignal$Builder.init(OneSignal.java:133)
                           at com.geektime.reactnativeonesignal.RNOneSignal.<init>(RNOneSignal.java:40)
                           at com.geektime.reactnativeonesignal.ReactNativeOneSignalPackage.createNativeModules(ReactNativeOneSignalPackage.java:23)
                           at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
                           at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:878)
                           at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
                           at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
                           at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                           at java.lang.Thread.run(Thread.java:818)
```

**Comment by Jatin0312** [comment]
How did u solve this Problem I'm also getting same problem

**Comment by jkasten2** [comment]
@Jatin0312 Can you post the exact error you are seeing like above? If it contains the same error on the top of the stack as the following:
```Java
java.lang.NumberFormatException: Invalid long:
```

Then this means you forgot the quotes  `"` around your app id.

**Comment by Jatin0312** [comment]
OneSignal AppId format is invalid.
 Example: 'b2f7f966-d8cc-11e4-bed1-df8f0is 5be55ba'
                                                                    
   java.lang.NumberFormatException: For input string: "AIzaSyBc"

This the error what I'm getting.
