### ISSUE TITLE
Metro Bundler failing with React Native V0.70

### ISSUE THREAD

**Issue by SectionTN** [OneSignal/react-native-onesignal#1430]
sorry i couldn't reproduce the issue at this moment, so please anyone can try OneSignal with RN70?

i remember that i saw something like `OneSignal not found within the project`.

sorry for the inconvenience issue.

**Comment by emawby** [comment]
@SectionTN Thank you for reaching out we will try to reproduce. When you say you cannot reproduce do you mean that it failed but then you got it working? Or it failed and so you downgraded RN?

**Comment by SectionTN** [comment]
@emawby it failed so i downgraded my RN version, I'm on a limited network so i'm sorry that i can't re-upgrade again and reproduce the problem, thank you.

**Comment by SectionTN** [comment]
@emawby sorry for the ping, any updates on this ?

**Comment by emawby** [comment]
@SectionTN I am not able to reproduce this issue. If you have any reproduction steps or more details on the error that would be helpful!

**Comment by SectionTN** [comment]
okay I'll try to reproduce again and tell you

**Comment by SectionTN** [comment]
@emawby I have re-upgraded again to 0.70.1 and got the same thing
error: 
```
error: Error: Unable to resolve module react-native-onesignal from /home/section/Documents/GitHub/MoonMeet-CrossPlatform/index.js: react-native-onesignal could not be found within the project or in these directories:
  node_modules
  ../../../node_modules
   7 |  */
   8 | import {AppRegistry} from 'react-native';
>  9 | import OneSignal from 'react-native-onesignal';
     |                        ^
  10 | import App from './App';
  11 | import {name as MoonMeet} from './app.json';
  12 | import {ONESIGNAL_APP_ID} from './src/secrets/sensitive';
    at ModuleResolver.resolveDependency (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:178:15)
    at DependencyGraph.resolveDependency (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at async traverseDependenciesForSingleFile (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/graphOperations.js:204:3)
    at async DeltaCalculator._getChangedDependencies (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:208:25)
    at async DeltaCalculator.getDelta (/home/section/Documents/GitHub/MoonMeet-CrossPlatform/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:90:16)
```
screenshot:
![image](https://user-images.githubusercontent.com/73752904/190625704-38156478-93f8-42e4-a8e5-212773c3c821.png)

steps: I have a project using RN 0.69.5 and upgraded to 0.70 or 0.70.1 using react native community upgrade helper.
if you want to check out any file of the project, see https://github.com/MoonMeet/MoonMeet-CrossPlatform

**Comment by SectionTN** [comment]
see here for more info, it's not a one signal problem.
https://github.com/facebook/react-native/issues/34712
