### ISSUE TITLE
[Bug]: After upgrading android to 31 app crashes while receiving push notifications

### ISSUE THREAD

**Issue by janandaraj** [OneSignal/react-native-onesignal#1467]
### What happened?

Recently upgraded android target version to 31 
after android upgrade app crashes while receiving push notification on android
With 3.x.x Latest Version

**Log from Android studio:**
Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.IllegalArgumentException: com.app.beachrunners: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### Steps to reproduce?

```Markdown
"react-native-onesignal": "3.9.4"
"react-native": "0.61.5",
build.gradle
"compileSdkVersion = 31"
"targetSdkVersion = 31"
```
Cause after upgrading android from 30 to 31

Android - crash
iOS - Working Fine

### What did you expect to happen?

Should receive push notification on android without crash, please help out with patches or fixes, project setup is not ready to upgrade for 4.x.x

### React Native OneSignal SDK version

3.9.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
 --------- beginning of crash
2023-01-04 10:19:32.077 15599-15599/com.app.beachrunners E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.beachrunners, PID: 15599
    java.lang.RuntimeException: Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.IllegalArgumentException: com.app.beachrunners: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4520)
        at android.app.ActivityThread.access$1900(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2219)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8248)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
     Caused by: java.lang.IllegalArgumentException: com.app.beachrunners: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:651)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:638)
        at com.onesignal.GenerateNotification.getNewActionPendingIntent(GenerateNotification.java:195)
        at com.onesignal.GenerateNotification.createGenericPendingIntentsForNotif(GenerateNotification.java:404)
        at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:388)
        at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:116)
        at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:115)
        at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:98)
        at com.onesignal.GcmBroadcastReceiver.startGCMService(GcmBroadcastReceiver.java:138)
        at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:129)
        at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:70)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4504)
        	... 9 more

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janandaraj** [comment]
Closing this issue, hence trying to upgrade react-native-onesignal@4.5.0, if any issues occur will raise new issue
