### ISSUE TITLE
[Bug]: App crash when trying to request notification permission

### ISSUE THREAD

**Issue by nathanael-anstett** [OneSignal/react-native-onesignal#1538]
### What happened?

Hello,

After adding onesignal to a lot of react native applications, this is the first time I encounter such an issue which seems to be related to the native part.

I installed `react-native-onesignal` package and followed the setup guide, but when trying to request for push permission on Android my app crashes (debug and release), and I need to check the logcat to retrieve the error details.

On iOS, everything is working great.

Thank you in advance for your help,

### Steps to reproduce?

```Markdown
1. Install package with `yarn add react-native-onesignal`
2. Check android configuration https://documentation.onesignal.com/docs/react-native-sdk-setup#step-3-install-for-android-using-gradle-for-android-apps
3. Launch app and use `OneSignal.promptForPushNotificationsWithUserResponse();`
```

### What did you expect to happen?

I expected the push permission prompt to display

### React Native OneSignal SDK version

4.5.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
When initializing the sdk with `setAppId`, I get a first error in logcat but this does not cause the app to crash :

`
Unknown error getting FCM Token
                                                                                                    java.lang.Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.messaging.FirebaseMessaging.getToken()' on a null object reference
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:133)
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.messaging.FirebaseMessaging.getToken()' on a null object reference
                                                                                                    	at com.onesignal.PushRegistratorFCM.getTokenWithClassFirebaseMessaging(PushRegistratorFCM.java:160)
                                                                                                    	at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:110)
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37) 
                                                                                                    	at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
`

Once I request push permission with `OneSignal.promptForPushNotificationsWithUserResponse();` (I do it by pressing a button so even after 10 seconds the crash occurs), I get the following error :

`
Exception in native call
                                                                                                    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.pass.tamaa.demo/com.onesignal.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2158)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1805)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5470)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5428)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5926)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5893)
                                                                                                    	at com.onesignal.PermissionsActivity$2.available(PermissionsActivity.java:189)
                                                                                                    	at com.onesignal.ActivityLifecycleHandler.addActivityAvailableListener(ActivityLifecycleHandler.java:225)
                                                                                                    	at com.onesignal.PermissionsActivity.startPrompt(PermissionsActivity.java:197)
                                                                                                    	at com.onesignal.NotificationPermissionController.prompt(NotificationPermissionController.kt:70)
                                                                                                    	at com.onesignal.OneSignal.promptForPushNotifications(OneSignal.java:2864)
                                                                                                    	at com.geektime.rnonesignalandroid.RNOneSignal.promptForPushNotificationsWithUserResponse(RNOneSignal.java:473)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rares-lupascu** [comment]
are u sure u did not install ver 5.0.0 since that was launched 2 days ago when this ticket was opened? :) just asking

**Comment by jennantilla** [comment]
@nathanael-anstett just following up to see if you saw @rares-lupascu's suggestion? Can you please verify which version of the SDK you are using?

Thanks!

**Comment by nathanael-anstett** [comment]
Hello, thank you for your answers @rares-lupascu and @jennantilla. I double checked and I confirm that the 4.5.1 is installed. In the end it does not seem to be related to this package because this problem appeared with other third libraries. Thank you for your help :)
