### ISSUE TITLE
[Bug]: Android crashing on start: error: Could not invoke OneSignal.*

### ISSUE THREAD

**Issue by alimek** [OneSignal/react-native-onesignal#1564]
### What happened?

Android release build is crashing when executing 

```ts
OneSignal.initialize("ONE_SIGNAL_APP_ID");
```

with error: 
```
java.lang.RuntimeException: Could not invoke OneSignal.initialize
```

app code:

```ts
import { LogLevel, OneSignal } from 'react-native-onesignal';

OneSignal.Debug.setLogLevel(LogLevel.Verbose);
OneSignal.initialize(ONE_SIGNAL_APP_ID);
```

Same code works without problem when app is built in debug mode.

Generally it fails when any method form NativeModule, no matter what I execute first, its faling with same error but just different method.

### Steps to reproduce?

```Markdown
Not sure yet, I think i migrated everything from https://github.com/OneSignal/react-native-onesignal/blob/major_release_5.0.0/MIGRATION_GUIDE.md

iOS is working fine, Android release mode is just crashing.
```

### What did you expect to happen?

Release build will not crash and OneSignal will be initialized.

### React Native OneSignal SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
java.lang.RuntimeException: Could not invoke OneSignal.initialize
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:193)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:148)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:149)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:148) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    Caused by: java.lang.Exception: Service class hg.b could not be instantiated
                                                                                                    	at xf.c.h(ServiceProvider.kt:59)
                                                                                                    	at hh.a.k(OneSignalImp.kt:79)
                                                                                                    	at rf.d.i(OneSignal.kt:17)
                                                                                                    	at com.onesignal.rnonesignalandroid.RNOneSignal.initialize(RNOneSignal.java:30)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:149) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:148) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Romick2005** [comment]
@holmesal can you please check if [this](https://github.com/OneSignal/react-native-onesignal/issues/1550#issuecomment-1723727016) solve the issue?

**Comment by alimek** [comment]
@Romick2005 yes, it does the trick, thanks for info!

**Comment by evo-sampath** [comment]
@Romick2005 thanks for the solution and can you please elaborate the solution by what it will do, do we get any side effects on this solution

**Comment by Romick2005** [comment]
If code work in dev debug, but not in release mode, usually it is caused that during optimization some java classes were not included as not used. You can force react native to avoid optimization for specific classes with [proguard](https://reactnative.dev/docs/signed-apk-android) rules.

Proguard is a tool that can slightly reduce the size of the APK.
