### ISSUE TITLE
FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by krunalray** [OneSignal/react-native-onesignal#1566]
### How can we help?

I migrate 4.3.6 to 5.0.0 and follow the Android SDK Setup instruction.

i used
"react-native": "0.64.0",

buildToolsVersion = "34"
minSdkVersion = 21
compileSdkVersion = 34
targetSdkVersion = 34
ndkVersion = "23.1.7779620"
kotlin_version = '1.9.0'

when i build the release apk and start the app then suddenly it's crash and give me error
`FATAL EXCEPTION: mqt_native_modules

com.facebook.react.bridge.NativeArgumentsParseException: OneSignal.setLogLevel got 2 arguments, expected 1

FATAL EXCEPTION: mqt_native_modules
Process: com.student.project, PID: 9884
com.facebook.react.bridge.NativeArgumentsParseException: OneSignal.setLogLevel got 2 arguments, expected 1
at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:332)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
at java.lang.Thread.run(Thread.java:1012)`

in debug mode i'm not getting any kind of error and working fine.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by skam22** [comment]
@krunalray as the error says, you're calling setlogLevel() with two arguments (version 4 syntax) instead of one argument (v5 syntax).

It should look like this:

```javascript
import {OneSignal, LogLevel} from 'react-native-onesignal';
OneSignal.Debug.setLogLevel(LogLevel.Verbose);
```

**Comment by usamaabutt** [comment]
I am also getting this [issue](https://github.com/OneSignal/react-native-onesignal/issues/1691)

**Comment by jennantilla** [comment]
Thanks @skam22 for the help! @krunalray let us know if you are still having issues.

@usamaabutt I've responded to the other linked issue requesting more details.

I'm going to close out this issue since the original problem should already be addressed.
