### ISSUE TITLE
[Bug]: Crash  ModelStore.persist java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Chasty** [OneSignal/react-native-onesignal#1578]
### What happened?

Crashlytics are reporting those crashes.

### Steps to reproduce?

```Markdown
-
```

### What did you expect to happen?

-

### React Native OneSignal SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
com.onesignal.common.modeling
ModelStore.kt:140

Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
       at java.util.ArrayList$Itr.next(ArrayList.java:982)
       at com.onesignal.common.modeling.ModelStore.persist(ModelStore.kt:140)
       at com.onesignal.common.modeling.ModelStore.addItem(ModelStore.kt:108)
       at com.onesignal.common.modeling.ModelStore.addItem$default(ModelStore.kt:98)
       at com.onesignal.common.modeling.ModelStore.add(ModelStore.kt:46)
       at com.onesignal.common.modeling.IModelStore$DefaultImpls.add$default(IModelStore.kt:37)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt:76)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueue(OperationRepo.kt:60)
       at com.onesignal.core.internal.operations.IOperationRepo$DefaultImpls.enqueue$default(IOperationRepo.kt:16)
       at com.onesignal.core.internal.operations.listeners.SingletonModelStoreListener.onModelUpdated(SingletonModelStoreListener.kt:51)
       at com.onesignal.common.modeling.SingletonModelStore$onModelUpdated$1.invoke(SingletonModelStore.kt:50)
       at com.onesignal.common.modeling.SingletonModelStore$onModelUpdated$1.invoke(SingletonModelStore.kt:50)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:44)
       at com.onesignal.common.modeling.SingletonModelStore.onModelUpdated(SingletonModelStore.kt:50)
       at com.onesignal.common.modeling.ModelStore$onChanged$1.invoke(ModelStore.kt:74)
       at com.onesignal.common.modeling.ModelStore$onChanged$1.invoke(ModelStore.kt:74)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:44)
       at com.onesignal.common.modeling.ModelStore.onChanged(ModelStore.kt:74)
       at com.onesignal.common.modeling.Model$notifyChanged$1.invoke(Model.kt:295)
       at com.onesignal.common.modeling.Model$notifyChanged$1.invoke(Model.kt:295)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:44)
       at com.onesignal.common.modeling.Model.notifyChanged(Model.kt:295)
       at com.onesignal.common.modeling.Model.notifyChanged(Model.kt:300)
       at com.onesignal.common.modeling.Model.setOptAnyProperty(Model.kt:200)
       at com.onesignal.common.modeling.Model.setOptAnyProperty$default(Model.kt:187)
       at com.onesignal.common.modeling.MapModel.put(MapModel.kt:47)
       at com.onesignal.common.modeling.MapModel.put(MapModel.kt:8)
       at com.onesignal.user.internal.UserManager.addTag(UserManager.kt:173)
       at com.onesignal.rnonesignalandroid.RNOneSignal.addTag(RNOneSignal.java:551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Chasty, thanks for reporting this issue. I will investigate along with your other crash report #1579

**Comment by arthurgeron-work** [comment]
Can we get a status on this? This crash is already impacting 10% of our user base.
![Captura de Tela 2023-10-11 às 08 56 20](https://github.com/OneSignal/react-native-onesignal/assets/71399856/161c9c65-505d-4f95-a14c-44e73329d274)

**Comment by theonetheycallneo** [comment]
@arthurgeron-work Yes, we are seeing the same...

![Poker_Power_-_Crashlytics_-_Firebase_console](https://github.com/OneSignal/react-native-onesignal/assets/367806/13d0b282-44e5-41c4-a3d2-fc1ccbc6dd21)

**Comment by nan-li** [comment]
Hi all, I apologize for any delay,

We have identified the cause and are working on the fix for all the methods this crash is reported.

**Comment by uasghar-smile** [comment]
Hi @nan-li I hope you are doing well. I am also getting crash and looking forward to fix it. Is there any chance to get a temp or permanent fix for it

I have reported this issue here with detail.
[Issue detail](https://github.com/OneSignal/react-native-onesignal/issues/1587#issuecomment-1990843389)

**Comment by jennantilla** [comment]
Hello everyone! These crashes should now be resolved. Please try updating to the [latest version](https://github.com/OneSignal/react-native-onesignal/releases/tag/5.2.0) of our SDK and let us know if you are still having any issues. Thanks!
