### ISSUE TITLE
[Bug]: Expo Eas Build Problem Xcode 15

### ISSUE THREAD

**Issue by hasanaktas** [OneSignal/react-native-onesignal#1595]
### What happened?

I was able to build in Xcode 14, but after updating to version 15, I started getting errors.

![image](https://github.com/OneSignal/react-native-onesignal/assets/30148248/6dfc0f57-7263-4028-bbff-5ecde0c06bde)

### Steps to reproduce?

```Markdown
"react-native": "0.72.6"
"expo": "^49.0.16"
"onesignal-expo-plugin": "^2.0.2"
"react-native-onesignal": "^5.0.2",
```

### What did you expect to happen?

✅ Eas build is successful on xcode 14 on expo server.

✅  Eas build is successful on xcode 14 on my own computer.

 ❌  Eas build fails on xcode 15 on expo server. (    "image": "latest" )

 ❌  Eas build fails on xcode 15 on my own computer.

### React Native OneSignal SDK version

5.0.2

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
[INSTALL_PODS] Using Expo modules
[INSTALL_PODS] [Expo] Enabling modular headers for pod ExpoModulesCore
[INSTALL_PODS] [Expo] Enabling modular headers for pod ReactCommon
[INSTALL_PODS] [Expo] Enabling modular headers for pod React-Core
[INSTALL_PODS] [Expo] Enabling modular headers for pod React-RCTAppDelegate
[INSTALL_PODS] [Expo] Enabling modular headers for pod expo-dev-menu-interface
[INSTALL_PODS] [Expo] Enabling modular headers for pod EXManifests
[INSTALL_PODS] [Expo] Enabling modular headers for pod EXUpdatesInterface
[INSTALL_PODS] [Expo] Enabling modular headers for pod expo-dev-menu
[INSTALL_PODS] [Expo] Enabling modular headers for pod RCT-Folly
[INSTALL_PODS] [Expo] Enabling modular headers for pod expo-dev-launcher
[INSTALL_PODS] [Expo] Enabling modular headers for pod SDWebImage
[INSTALL_PODS] [Expo] Enabling modular headers for pod SDWebImageWebPCoder
[INSTALL_PODS] [Expo] Enabling modular headers for pod SDWebImageAVIFCoder
[INSTALL_PODS] [Expo] Enabling modular headers for pod SDWebImageSVGCoder
[INSTALL_PODS] [Expo] Enabling modular headers for pod EXStructuredHeaders
[INSTALL_PODS] [Expo] Enabling modular headers for pod EASClient
[INSTALL_PODS] [Expo] Enabling modular headers for pod ReachabilitySwift
[INSTALL_PODS] [Expo] Enabling modular headers for pod ASN1Decoder
[INSTALL_PODS] Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/hasanaktas/.nvm/versions/node/v18.18.0/bin/node
[INSTALL_PODS] Auto-linking React Native modules for target `hipicondev`: RNCAsyncStorage, RNFlashList, RNGestureHandler, RNGoogleSignin, RNReanimated, RNSVG, RNScreens, lottie-react-native, react-native-adjust, react-native-date-picker, react-native-netinfo, react-native-onesignal, react-native-safe-area-context, and react-native-webview
[INSTALL_PODS] Framework build type is static library
[INSTALL_PODS] [Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[INSTALL_PODS] Analyzing dependencies
[INSTALL_PODS] Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[INSTALL_PODS] [Codegen] Found FBReactNativeSpec
[INSTALL_PODS] Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[INSTALL_PODS] [Codegen] Found rncore
[INSTALL_PODS] Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
[INSTALL_PODS] Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[INSTALL_PODS] Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[INSTALL_PODS] [Hermes] Using the release tarball from Maven Central
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     OneSignalXCFramework (< 6.0, >= 5.0)
[INSTALL_PODS]     react-native-onesignal (from `../node_modules/react-native-onesignal`) was resolved to 5.0.2, which depends on
[INSTALL_PODS]       OneSignalXCFramework (= 5.0.2)
[INSTALL_PODS] Specs satisfying the `OneSignalXCFramework (< 6.0, >= 5.0), OneSignalXCFramework (= 5.0.2)` dependency were found, but they required a higher minimum deployment target.
[INSTALL_PODS] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `0160B7B8F0E540219AE99703` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
[INSTALL_PODS] 
Error: pod install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at spawnAsync (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/turtle-spawn/dist/index.js:16:47)
    at installPods (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/ios/pod.js:11:38)
    at /Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/builders/ios.js:70:41
    at BuildContext.runBuildPhase (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/context.js:101:34)
    at buildAsync (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/builders/ios.js:69:19)
    at async runBuilderWithHooksAsync (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/builders/common.js:12:13)
    at async Object.iosBuilder (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/@expo/build-tools/dist/builders/ios.js:29:16)
    at async buildIosAsync (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/eas-cli-local-build-plugin/dist/ios.js:66:12)
    at async buildAsync (/Users/hasanaktas/.npm/_npx/63539ccd18962a9d/node_modules/eas-cli-local-build-plugin/dist/build.js:54:29)

Build failed
Unknown error. See logs of the Install pods build phase for more information.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @hasanaktas thank you for your patience! Just an update that we are looking into this and will get back to you as soon as possible.

**Comment by andismith** [comment]
Hi, is there any update on this issue please?

**Comment by ovidb** [comment]
@jennantilla please let us know if there are any updates on this? 

With v4 we have duplicated notifications because we are using both OneSignal and Expo Notifications. The suggestion from your support team was to update to v5, but unfortunately we are getting the same error which leaves us quite stuck.

We are now at the point where we are considering if we should remove OneSignal SDK to get around this issue but that would require quite a bit of work on our end.

**Comment by ovidb** [comment]
@jennantilla no updates on this? This is still happening on our end and its been almost 3 months now

**Comment by haelsisy** [comment]
Did you manage to fix this?

**Comment by hasanaktas** [comment]
@haelsisy 
Because there were problems with every Expo update, we stopped using OneSignal and switched to Expo push notification.

**Comment by djaffer** [comment]
still getting this error

**Comment by fadi-george** [comment]
Hey all,
Apologies but the `onesignal-expo-plugin` is deprecated and no longer maintained. As such, we don't plan to fix issues that are related to it. Please use the bare `react-native-onesignal` library instead.
