### ISSUE TITLE
[Bug]: In-App Messages crash Android devices (fine on iOS) - NullPointerException on HashMap.keySet()

### ISSUE THREAD

**Issue by VirtualDOMinic** [OneSignal/react-native-onesignal#1643]
### What happened?

Recently (but I can't pin down when it started), when testing in-app messages on Android devices, the app crashes and our Sentry reports `NullPointerException com.onesignal.OSInAppMessageInternal in toJSONObject`, `Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference`.

I have yet to test older/newer versions of the library due to time constraints, but I plan to.

<img width="950" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/19417581/d9e71384-88aa-4b45-96e2-0941ed030160">

### Steps to reproduce?

```Markdown
1. Build a release version of an app (yet to confirm if bug happens in debug mode on simulator) that uses `react-native-onesignal` v4.5.2
2. Open the app on a real Android device (we've tried on various devices and Android versions, including Galaxy S23 on Android 14, Huawai P30, Galaxy S8 and an older Sony Xperia, all on Android <=13)
3. Accept push notification permissions on the device
4. Add device to test subscriptions in OneSignal dashboard
5. If you like, send a test push notification to confirm they work (they do, no crash)
6. Ensure the app is open on your device, and pen the in-app message editor, create any sort of in-app message and then do "Send Test In-App" from the editor, selecting your Android device
7. The in-app message will cause the app to crash suddenly, within a second or so of the message appearing. Sometimes before the message appeared.
```

### What did you expect to happen?

I expected the in-app message to appear, and to be able to interact with it, dismiss it, or leave it visible, without the app crashing.

### React Native OneSignal SDK version

4.5.2

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference
    at com.onesignal.OSInAppMessageInternal.toJSONObject(OSInAppMessageInternal.java:159)
    at com.geektime.rnonesignalandroid.RNOneSignal$13.onWillDisplayInAppMessage(RNOneSignal.java:737)
    at com.onesignal.OSInAppMessageController.onMessageWillDisplay(OSInAppMessageController.java:369)
    at com.onesignal.OSInAppMessageController$14.onSuccess(OSInAppMessageController.java:879)
    at com.onesignal.OSInAppMessageRepository$7.onSuccess(OSInAppMessageRepository.java:142)
    at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
    at java.lang.Thread.run(Thread.java:929)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VirtualDOMinic** [comment]
Currently hypothesising/hoping that this might ONLY happen when sending **test message**s (step 6 in steps to reproduce) rather than real in-app messages. 

And when I look at the code from v4, it seems there is only one `HashMap`: https://github.com/OneSignal/react-native-onesignal/blob/6d052e92b7cc20bf4c9361688302aa0dac27e556/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java#L153 -- `notificationReceivedEventCache`. Maybe there's something not created/handled correctly when a notification is used to trigger a test IAM 🤔

**Comment by nagasailokesh-toddle** [comment]
Hi, found any solution for this?

**Comment by fadi-george** [comment]
Hi all, apologies this issue has gone stale; the team is no longer actively supporting and patching the v4 / v3 major version of this SDK.
I recommend upgrading to v5 of our SDK. Please see our [documentation](https://documentation.onesignal.com/docs/en/user-model-migration-guide) on the new user model and migration steps, and let us know if we can help you with the transition.
