### ISSUE TITLE
Crash: PermissionsActivity.reregisterCallbackHandlers 

### ISSUE THREAD

**Issue by aneena-thomas** [OneSignal/react-native-onesignal#1661]
### What happened?

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.lanch/com.onesignal.PermissionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference

### Steps to reproduce?

```Markdown
Install the app on Android 8 or below 10 versions
```

### What did you expect to happen?

Should not crash

### React Native OneSignal SDK version

4.3.7

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @aneena-thomas thanks for your patience. Is this still a concern for you? If so can you please provide the full stack trace so we can take a deeper look? Appreciate it!

**Comment by andronixmd** [comment]
I have the same problem. 
react-native-onesignal - 4.5.2
react-natve - 0.66.5

Device info:
Model - Nexus 5X
OS version - 8.1.0
Android ApiLevel - 27

Here's the stack trace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appname/com.onesignal.PermissionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
        at com.onesignal.PermissionsActivity.reregisterCallbackHandlers(PermissionsActivity.java:109)
        at com.onesignal.PermissionsActivity.handleBundleParams(PermissionsActivity.java:100)
        at com.onesignal.PermissionsActivity.onCreate(PermissionsActivity.java:82)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by fadi-george** [comment]
Hi all, apologies this issue has gone stale; the team is no longer actively supporting and patching the v4 major version of this SDK.
I recommend to upgrade to v5 of our SDK. Please see our [documentation](https://documentation.onesignal.com/docs/en/user-model-migration-guide) on the new user model and migration steps, and let us know if we can help you with the transition.
