### ISSUE TITLE
OneSignal.inFocusDisplaying(0) don't work 100% of the time

### ISSUE THREAD

**Issue by note89** [OneSignal/react-native-onesignal#193]
Hello sometimes in our app we get that alert box in our app. 
Cannot really pinpoint when yet.

**Comment by avishayil** [comment]
@jkasten2

**Comment by jkasten2** [comment]
@note89 When it doesn't work can you check to see if there are any errors in the logcat? Also please let us know which version of the OneSignal SDK you are using.

**Comment by note89** [comment]
running `"react-native-onesignal": "3.0.2",`
I will see, need to start running logcat all the time then.

**Comment by arilitan** [comment]
also experiencing this issue

**Comment by note89** [comment]
Found this stacktrace on Crashalytics
```
Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'com.onesignal.OneSignal$OSInFocusDisplayOption com.onesignal.OneSignal$Builder.mDisplayOption' on a null object reference
       at com.onesignal.OneSignal.setInFocusDisplaying(OneSignal.java:1192)
       at com.geektime.rnonesignalandroid.RNOneSignal.inFocusDisplaying(RNOneSignal.java:111)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by jkasten2** [comment]
@note89 Thanks for the stack trace. Once I have the following finished it will definitely resolve this issue.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/163

**Comment by jjdp** [comment]
+1

**Comment by jkasten2** [comment]
@note89 @avishayil @arilitan @jjdp The OneSignal Android Native 3.4.4 SDK has been released with a fix for this. Re-syncing your gradle files from Tools > Android > `Sync Project with Gradle Files` should get you this version.
