### ISSUE TITLE
Android Crashes on getRegistrationId

### ISSUE THREAD

**Issue by JakeRawr** [OneSignal/react-native-onesignal#257]
Hi, all

I am getting a lot of crashing from Android users when they open the app.
this is the error I got from Fabric crashlytics
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'org.json.JSONObject com.onesignal.OneSignalStateSynchronizer$UserState.syncValues' on a null object reference
       at com.onesignal.OneSignalStateSynchronizer.getRegistrationId(OneSignalStateSynchronizer.java:756)
       at com.onesignal.OneSignal.internalFireIdsAvailableCallback(OneSignal.java:1016)
       at com.onesignal.OneSignal.idsAvailable(OneSignal.java:998)
       at com.geektime.rnonesignalandroid.RNOneSignal.configure(RNOneSignal.java:97)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

Any help is appreciated

**Comment by jkasten2** [comment]
@JakeRawr The OneSignal Android native 3.5.7 SDK was released today that fixes this issue.
