### ISSUE TITLE
Android: OneSignal AppId format is invalid -- java.lang.String.split(java.lang.String) on a null object reference

### ISSUE THREAD

**Issue by sunweiyang** [OneSignal/react-native-onesignal#373]
I believe this invalid app ID issue is different from #135.

Observed on RN 0.50.4 - 0.52.1, on Android 7.0 - 8.0 (on both Pixel emulator and Samsung Galaxy Note 5); this issue is not necessarily limited to these versions/platforms.

I'm using react-native-onesignal for both my Android and iOS versions of my app. The iOS version works fine, but Android is having an issue with initializing OneSignal.

Here is the defaultConfig section of my `app/build.gradle`, which seemed to work for some time:
```
    defaultConfig {
        multiDexEnabled true
        multiDexKeepProguard file('proguard-rules.pro')
        applicationId "com.example"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 32
        versionName "1.9"
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        resValue "string", "build_config_package", "com.example"
        manifestPlaceholders = [onesignal_app_id: "MY_ONESIGNAL_APP_ID",
                                onesignal_google_project_number: "MY_FIREBASE_SENDER_ID"]
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
```

However, for recent react-native-onesignal versions (for example, 3.0.7 and 3.0.9), I've been getting this error during OneSignal initialization:

```
01-25 01:34:05.748 6205-6277/com.example E/OneSignal: OneSignal AppId format is invalid.
                                                                   Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
                                                                   
                                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
                                                                       at java.util.UUID.fromString(UUID.java:192)
                                                                       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:62)
                                                                       at com.onesignal.OneSignal.init(OneSignal.java:492)
                                                                       at com.onesignal.OneSignal.init(OneSignal.java:468)
                                                                       at com.onesignal.OneSignal.access$000(OneSignal.java:79)
                                                                       at com.onesignal.OneSignal$Builder.init(OneSignal.java:283)
                                                                       at com.geektime.rnonesignalandroid.RNOneSignal.initOneSignal(RNOneSignal.java:72)
                                                                       at com.geektime.rnonesignalandroid.RNOneSignal.onHostResume(RNOneSignal.java:291)
                                                                       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:186)
                                                                       at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:687)
                                                                       at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:722)
                                                                       at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:997)
                                                                       at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:113)
                                                                       at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:965)
                                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                       at java.lang.Thread.run(Thread.java:764)
```

**Comment by avishayil** [comment]
Make sure you're using the correct app id format by copying the app id from your account.
For the project number, please use "REMOTE", as the official documentation indicates.

**Comment by ospfranco** [comment]
I'm experiencing the same problem, my app_id and the project_number were correctly configured, at it seemed to be working fine, until yesterday we received a crash report, and today (after changing some gradle configuration) the app won't start when running on device

**Comment by sunweiyang** [comment]
@ospfranco I found out what caused my problem. It came from OneSignal's official troubleshooting docs:
https://documentation.onesignal.com/docs/troubleshooting-android

In that page's "ERROR: AppId format is invalid" section, it says:
```
Make sure you are not replacing the <application> tag in your AndroidManifest.xml with tools:node="replace"
```
I found out that my error happened because I have used `tools:node="replace"` in my AndroidManifest.xml (to work around an issue with a different RN 3rd party module). Once I got rid of `tools:node="replace"`, everything worked as expected.

**Comment by ospfranco** [comment]
ah that makes sense... now that is a pickle, we need the replace tools tag for another library... thanks for the help!

P.S. I actually got around the problem by not using the manifest placeholder option and just putting the appId in the manifest file, but haven't tested in production yet, so...

**Comment by Andriiklymiuk** [comment]
So, have someone solved this issue?

**Comment by jkasten2** [comment]
@Andriiklymiuk Can you confirm that the `<application>` tag in your `AndroidManifest.xml` does not have `tools:node="replace"`? This is the most common cause of this specific error.

If not I recommend sharing your root `build.gradle`, `app/build.gradle`, and your `AndroidManifest.xml` so we can check for any other possible issues. Or if are able to reproduce the issue with a new project with a specific set of plugins let us know.

**Comment by Andriiklymiuk** [comment]
@jkasten2 Yes, I have tools:node="replace" and without it project doesn't work.

**Comment by jkasten2** [comment]
@Andriiklymiuk Using `tools:node="replace"` on `<application>` breaks OneSignal and as well as a number of other native Android plugins as it omits any services, receivers, actives , meta-data, etc that they try to include.

What errors / issues do you get if you remove `tools:node="replace"`? If you can provide the above details from my last comment we should be able to find the root of the problem you get afterwards.

**Comment by Andriiklymiuk** [comment]
@jkasten2  Well, I am deleting it and receiving the following errors. I guess it is some problems in my project, thanks)

`Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.`

**Comment by Andriiklymiuk** [comment]
@jkasten2 Thanks! It was really nice suggestion about `tools:node="replace"`
So I found workaround to this problem, which works for our project:
1. `tools:node="replace"` -- deleted in AndroidManifest, as you mentioned.
2. added in build.gradle (app)
```
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '26.1.0'
                }
            }
        }
    } 
```

**Comment by jkasten2** [comment]
@Andriiklymiuk Good to hear!

We recommend the following gradle plugin instead of the `resolutionStrategy` gradle snippet you have so you don't have to update the `26.1.0` value when plugins change dependencies in the future.

Add to line 1 of your `app/build.gradle`
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```
It will also fix gms and firebase versions to be in alignment too.

**Comment by Andriiklymiuk** [comment]
@jkasten2 Oh, thanks a lot) So I ll write it here the way it worked for me, just  in case anybody will face same issue.
```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
buildscript {
  repositories {
    ...
    maven { url 'https://plugins.gradle.org/m2/' }
  }

  dependencies {
    ...
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.8.2, 0.99.99]'
  }

}
```
