### ISSUE TITLE
App freezes on importing onesignal. 

### ISSUE THREAD

**Issue by arrygoo** [OneSignal/react-native-onesignal#420]
We've had an app that's been in production for few months. Without changing anything, now our ios app freezes on splash screen with the following error.

I opened this issue because it seems like it's more react-native related than ios. 

We're currently on version ` "react-native-onesignal": "^3.0.5",` , but upgrading onesignal to the latest version didn't fix or change the behaviour of issue either. 

The error happens on this line:

`import OneSignal from 'react-native-onesignal';` 

```
TypeError: this._nativeModule.addListener is not a function. (In 'this._nativeModule.addListener(e)', 'this._nativeModule.addListener' is undefined)
  at handleEventBroadcast(/home/runner/seam/mobile/node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:38:26)
  at factory(/home/runner/seam/mobile/node_modules/react-native-onesignal/index.js:28:29)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/screens/HomeScreen/index.js:30:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/navigation/Home.js:4:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/navigation/Tabs.js:13:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/navigation/Main.js:11:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/navigation/Root.js:6:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at factory(/home/runner/seam/mobile/main.js:9:1)
  at loadModuleImplementation(/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:191:5)
  at ? (/home/runner/seam/mobile/node_modules/metro-bundler/src/Resolver/polyfills/require.js:131:21)
  at global code(require-0.js:1:1)
```

Since this is happening on the line that's importing one-signal, I don't think the problem is with how we use the package. How can we narrow down this issue further?

**Comment by ghost** [comment]
@arrygoo same here.

**Comment by arrygoo** [comment]
@kytwb 
My issue turned out to be that I had one signal added to package.json like `^3.0.5` instead of `~3.0.5`. 

Looks like there's a native change `3.1.0`, so having `^3.0.5` will make your javascript out of sync with native.

**Comment by ghost** [comment]
_**Edit:**_ Working now with `"react-native-onesignal": "^3.1.2"`.
