### ISSUE TITLE
React-native + expo + onesignal crashes the app on intialization (Android)

### ISSUE THREAD

**Issue by faustoct1** [OneSignal/react-native-onesignal#440]
Any related bug ? The app just crashes when add onesignal.

got this error from logcat not sure if it means anything

````
03-28 16:42:49.588 2881-2905/? D/ViewRootImpl@2f61b07[social]: dispatchDetachedFromWindow
03-28 16:42:49.591 2881-2905/? W/WindowManager: Failed looking up window
                                                java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@d6fd434 does not exist
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10720)
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10711)
                                                    at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2717)
                                                    at com.android.server.wm.Session.remove(Session.java:218)
                                                    at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3752)
                                                    at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6692)
                                                    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4163)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:154)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.android.server.ServiceThread.run(ServiceThread.java:46)
````

**Comment by jkasten2** [comment]
@faustoct It doesn't look related, I don't see OneSignal in the stack trace or the message. Do you get this error when opening a notification or just each time the app is opened normally?

**Comment by faustoct1** [comment]
@jkasten2 just each time the app is opened normally. Without onesignal it works when add it crashes.

**Comment by faustoct1** [comment]
@jkasten2 I have no idea what to try next. Please, a little help my friend..

**Comment by jkasten2** [comment]
@faustoct Can you provide an example project reproducing the issue? Either a link to a zip or a public github repo will be helpful

**Comment by faustoct1** [comment]
@jkasten2 ok.. i'm gonna push the project so you can run locally..

**Comment by faustoct1** [comment]
@jkasten2 u can run from here https://github.com/faustoct/onesignaltest

**Comment by faustoct1** [comment]
@jkasten2 maybe it can show more details

````
W/AsyncCondition: Could not find listener for key: openExperienceActivity
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.linked4.app.social, PID: 28381
                  java.lang.RuntimeException: Unable to resume activity {com.linked4.app.social/host.exp.exponent.MainActivity}: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6776)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
                   Caused by: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                      at com.google.android.gms.common.zze.zzbp(Unknown Source)
                      at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
                      at com.google.android.gms.common.zzc.isGooglePlayServicesAvailable(Unknown Source)
                      at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
                      at host.exp.exponent.experience.BaseExperienceActivity.registerForNotifications(BaseExperienceActivity.java:244)
                      at host.exp.exponent.experience.ExperienceActivity.onResume(ExperienceActivity.java:192)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                      at android.app.Activity.performResume(Activity.java:7101)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6776) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 
````

**Comment by faustoct1** [comment]
@jkasten2 hi man just worked had to add the follow line to AndroidManifest.xml

`<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`

**Comment by jkasten2** [comment]
@faustoct That might fix the crash but your still going to have issues with OneSignal and most other Android SDKs / plugins due to another issue in your project.

After looking at your project I found `tools:node="replace"` in your `<application>` tag in your `android/app/src/main/AndroidManifest.xml`. This means any xml tags that plugins / SDK require will be omitted which will cause them not to work, including OneSignal. If you remove this it should solve the issue you had
https://github.com/faustoct/onesignaltest/blob/master/android/app/src/main/AndroidManifest.xml#L44

**Comment by faustoct1** [comment]
@jkasten2  got it.. can't remove otherwise the project does not compile..
I got the error
````
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_devRemoteKernelDebugApk'.
   > A problem occurred configuring project ':react-native-fetch-blob'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-fetch-blob'. Minimum required is 25.0.0
````

is there another way to solve it?

**Comment by jkasten2** [comment]
I don't see `react-native-fetch-blob` in your repo. Also it looks like you have `buildToolsVersion` set to `26.0.1`.
https://github.com/faustoct/onesignaltest/blob/master/android/app/build.gradle#L20

Is this error from the same project? If not you should be able to just update `buildToolsVersion` to `25.0.0` or newer in your `android/app/build.gradle`. `27.0.3` is the newest which is recommend.

**Comment by faustoct1** [comment]
@jkasten2 it seems to work.. will test the app and check it has a broken stuff. let u know. Will try ur suggestion.. thank you let u know soon..

**Comment by faustoct1** [comment]
@jkasten2 I didn't add react-native-fetch-blob to the example.. Doing my way got this error
````
E/OneSignal: OneSignal AppId format is invalid.
             Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'

             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
                 at java.util.UUID.fromString(UUID.java:192)
                 at com.onesignal.OSUtils.initializationChecker(OSUtils.java:63)
                 at com.onesignal.OneSignal.init(OneSignal.java:558)
                 at com.onesignal.OneSignal.init(OneSignal.java:534)
                 at com.onesignal.OneSignal.access$000(OneSignal.java:80)
                 at com.onesignal.OneSignal$Builder.init(OneSignal.java:315)
                 at com.geektime.rnonesignalandroid.RNOneSignal.initOneSignal(RNOneSignal.java:76)
                 at com.geektime.rnonesignalandroid.RNOneSignal.onHostResume(RNOneSignal.java:360)
                 at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:186)
                 at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:687)
                 at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:722)
                 at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:997)
                 at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:113)
                 at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:965)
                 at android.os.Handler.handleCallback(Handler.java:751)
                 at android.os.Handler.dispatchMessage(Handler.java:95)
                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                 at android.os.Looper.loop(Looper.java:154)
                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                 at java.lang.Thread.run(Thread.java:762)
````

**Comment by faustoct1** [comment]
@jkasten2 Worked! I had to edit the app/build.gradle and add 
````
    manifestPlaceholders = [
            'appAuthRedirectScheme': 'xxx',
            'onesignal_app_id': "yyy..",
            'onesignal_google_project_number': "REMOTE"
    ]

````

**Comment by jkasten2** [comment]
@faustoct Good to hear, glad I was able to help!

**Comment by Andriiklymiuk** [comment]
I have the same issue and placing my applicationId in appAuthRedirectScheme doesn't help either. Maybe someone solved the issue?

**Comment by faustoct1** [comment]
@Andriiklymiuk have u tried the steps described here? I mean
1) install react-native-onesignal (`yarn add react-native-onesignal`) + link (`react-native link react-native-onesignal`)
2) add `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />` to AndroidManifest.xml 
3) `update buildToolsVersion to 27.0.3 in your android/app/build.gradle.`
4) add to your app/build.gradle `manifestPlaceholders = ['appAuthRedirectScheme': 'xxx', 'onesignal_app_id': "yyy..", 'onesignal_google_project_number': "REMOTE"]`

**Comment by Andriiklymiuk** [comment]
@faustoct Thanks) These suggestions solved several problems in our project, but not all.
So I found workaround to the problem, which works for our project:

1. `tools:node="replace"` -- deleted in AndroidManifest
2. added in build.gradle (app)
```
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '26.1.0'
                }
            }
        }
    } 
```

**Comment by Nightsd01** [comment]
Hi everyone,

We've recently updated the OneSignal react-native SDK (3.2.0) so that it will no longer cause a crash if you run it in the Expo client.

Essentially, we've made it so that the SDK will check to make sure the native bridge exists before attempting to use it.

Unfortunately, the Expo client can't let us run native code (iOS restriction), so we can't actually use our iOS/Android SDK's. This means that when you call OneSignal functions like sendTags() from within an app running in the Expo client, nothing will happen. But at least it's better than instantly crashing when the app launches.

The SDK should start functioning correctly once you detach from expo and link. If you have any questions, please feel free to contact our support (I will see your ticket) by going to the onesignal dashboard and clicking the ? button.

**Comment by kenshinman** [comment]
Still not working. Crashes my app when i add `OneSignal.init("id")`
