### ISSUE TITLE
FATAL EXCEPTION: Firebase-FirebaseMessagingService

### ISSUE THREAD

**Issue by wayoff** [OneSignal/react-native-onesignal#559]
**Description:**
I'am working with react-native-onesignal but quite some time now and everything works find if it's iOS but when i switch to Android i got a ton of issues but manage to solve most of it. now i have one final issue which i'am currently lost, my issue state about firebase but i don't have firebase installed on my app but onesignal does which it's dependencies that 

- works:
  1) i manage to receive notification / normal / channel / with custom sound and i perfectly got the notification
  2) build debug / release apk works fine now

- issue:
  1) when i receive a notification. the app crashes

**Environment**

1) Versions:
    - RN: 0.55.4
    - RN-Onesignal: 3.2.4
2) use npm and 
    - followed the guideline on how to install it on android 
    - as well as going to the troubleshooting guide

3) `build.gradle`
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        maven { 
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        //classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.android.tools.build:gradle:2.2.+' // <- USE 2.2.+ version

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
```

4) `app/build.gradle`
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    
    defaultConfig {
        applicationId "se.digitaltolk"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    dexOptions {
        jumboMode true
    }

}

dependencies {
    compile project(':react-native-appstore-version-checker')
    compile project(':react-native-immediate-phone-call')
    compile project(':react-native-fabric')
    compile project(':react-native-onesignal')
    compile project(':react-native-file-viewer')
    compile project(':react-native-i18n')
    compile project(':react-native-restart')
    compile project(':react-native-fs')
    compile project(':react-native-doc-viewer')
    compile project(':react-native-device-info')
    compile project(':react-native-radial-gradient')
    compile project(':react-native-linear-gradient')
    compile project(':realm')
    compile project(':react-native-vector-icons')
    compile project(':react-native-orientation')

    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
      }
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-maps:+'
    compile "com.google.android.gms:play-services-location:+"

    compile project(':react-native-google-places')
    compile project(':react-native-geocoder')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-smart-splashscreen')

    compile project(':react-native-image-picker')
    compile project(':react-native-camera')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:26.0.1"
    compile ("com.facebook.react:react-native:0.55.4") { force = true }  // From node_modules
    
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        compile 'com.android.support:exifinterface:25.+'
        compile ('com.google.android.gms:play-services-vision:12.0.1') {
            force = true
        }
    }

    compile project(':react-native-image-picker')

    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }

    compile "com.google.android.gms:play-services-ads:+"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        // The Fabric Gradle plugin uses an open ended version to react
        // quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'io.fabric'
repositories {
    maven { url 'https://maven.fabric.io/public' }
}
```

**Android Log Cat:**
```
06-13 13:02:29.865  1959  1959 D DefaultPhoneNotifier: notifySignalStrength: mRegistry=com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy@6ccf64 ss=SignalStrength: 12 4 -90 -120 -80 -120 4 90 -100 -10 30 7 gsm|lte sender=Handler (com.android.internal.telephony.gsm.GSMPhone) {e9a642a}
06-13 13:02:29.884  6653  6772 E AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService
06-13 13:02:29.884  6653  6772 E AndroidRuntime: Process: se.digitaltolk, PID: 6653
06-13 13:02:29.884  6653  6772 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
06-13 13:02:29.884  6653  6772 E AndroidRuntime:  at com.google.firebase.iid.zzc.run(Unknown Source)
06-13 13:02:29.884  6653  6772 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 13:02:29.884  6653  6772 E AndroidRuntime:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 13:02:29.884  6653  6772 E AndroidRuntime:  at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
06-13 13:02:29.884  6653  6772 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:818)
06-13 13:02:29.884  1648  2655 I am_crash: [6653,0,se.digitaltolk,952680006,java.lang.AbstractMethodError,abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)",NULL,-1]
06-13 13:02:29.884  1648  2655 W ActivityManager:   Force finishing activity se.digitaltolk/.MainActivity
06-13 13:02:29.884  1648  2655 I am_finish_activity: [0,235597098,19,se.digitaltolk/.MainActivity,force-crash]
06-13 13:02:29.885  1240  1286 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
06-13 13:02:29.909  1648  2655 D         : HostConnection::get() New Host Connection established 0x7f4df5e36e20, tid 2655
```

**Comment by wayoff** [comment]
closing issue by adding:

```
compile 'com.google.android.gms:play-services-gcm:+'
compile 'com.google.firebase:firebase-core:+'
compile 'com.google.firebase:firebase-messaging:+'
```

on `build.gradle`
