### ISSUE TITLE
OneSignal.getPermissionSubscriptionState() returns null in some cases

### ISSUE THREAD

**Issue by GuiCavi** [OneSignal/react-native-onesignal#566]
### **Description:**

When using `getPermissionSubscriptionState`, it throws an error due to
https://github.com/geektimecoil/react-native-onesignal/blob/a56b0fe15c705c59f6510073feb63c4dbb13d79f/android/src/main/java/com/geektime/rnonesignalandroid/RNOneSignal.java#L221
returning null.

---

### **Environment**

From *yarn.lock*
OneSignal RNSDK:
```yml
react-native-onesignal@^3.0.7:
  version "3.0.7"
  resolved "https://registry.yarnpkg.com/react-native-onesignal/-/react-native-onesignal-3.0.7.tgz#d4fd7cb8297aada7e1a11abef311fb577d3f8428"
  dependencies:
    invariant "^2.2.2"
```
|    Platform    |     Variant         |
|:------------:|:--------------:|
| Android | Production |

---

### **Steps to Reproduce Issue:**

During tests, I wasn't able to reproduce the error, it was catch only in production by Sentry reports. Notice that the reports don't show any console print.

---

### **Anything else:**

[Link to imgur with a report from Sentry about the devices description](https://i.imgur.com/ttHscn4.png)

---

According to Sentry logs, this is the exception:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.onesignal.OSPermissionState com.onesignal.OSPermissionSubscriptionState.getPermissionStatus()' on a null object reference
    at com.geektime.rnonesignalandroid.RNOneSignal.getPermissionSubscriptionState(RNOneSignal.java:118)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:761)
```

I'm hoping there is a solution for this that I'm not seeing.

Thanks for any help.

**Comment by Nightsd01** [comment]
@GuiCavi This was fixed in a recent update to the OneSignal RN SDK about a month ago.

Please update to 3.2.4 and the issue should disappear.

**Comment by GuiCavi** [comment]
Thanks for the quick answer. I'll do the upgrade and if needed write a comment about it. I didn't find anything about the fix when first read the update.

Thanks again.

**Comment by edo1493** [comment]
I am on the latest and I keep seeing this in production.
