### ISSUE TITLE
Crash on Android when calling init() 

### ISSUE THREAD

**Issue by joeyscarim** [OneSignal/react-native-onesignal#586]
This issue was also opened and closed here https://github.com/geektimecoil/react-native-onesignal/issues/490#issuecomment-403284564 but this issue still exists, as the comments (mine included) show. I am opening this as a new issue to bring attention to it again.

**Description:**
When I call the function OneSignal.init(), my app crashes immediately. This only happens on Android builds. There are no issues on iOS builds.

**Environment**
my dependencies are as follows: 
```
  "dependencies": {
    "color": "1.0.3",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.6.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-onesignal": "^3.2.5",
    "react-navigation": "^2.5.5"
  }
```

**Steps to Reproduce Issue:**
### my root build.gradle:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
    }

}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

### my /app build.gradle:

```
buildscript {
   repositories {
       maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
   }
   dependencies {
       classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
   }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.nativebasekitchensink"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-onesignal')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

**Comment by Nightsd01** [comment]
@joeyscarim are you getting the same exact stack trace posted in #490? If the stacktrace you get is different can you please post it...?

Also, does the issue occur if you use native initialization (putting your app ID in your `build.gradle` instead of calling `init` from JS)? The steps to do this are shown in our [old readme](https://github.com/geektimecoil/react-native-onesignal/blob/a037801eb9960a38678cf592aa04b3d7849af785/README.md#adding-the-code)

**Comment by ashokkumar88** [comment]
@joeyscarim I was having the same issue. Then what I found that the `OneSignal.getTags()` was firing multiple times very rapidly from my js file. Then I applied a check in my js file to not fire getTags() more than once very rapidly. After that it is working fine.

**Comment by joeyscarim** [comment]
@Nightsd01 my stack trace looks different: 

```
07-18 12:09:32.227 4728-4780/com.nativebasekitchensink E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
                                                                         Process: com.nativebasekitchensink, PID: 4728
                                                                         java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.nativebasekitchensink. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                             at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                                             at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                             at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
                                                                             at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source)
                                                                             at com.google.firebase.iid.zzc.run(Unknown Source)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)
07-18 12:09:32.236 4728-4779/com.nativebasekitchensink W/System: ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art: Rejecting re-init on previously-failed class java.lang.Class<com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/customtabs/CustomTabsServiceConnection;
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void java.lang.Thread.run() (Thread.java:761)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.customtabs.CustomTabsServiceConnection" on path: DexPathList[[zip file "/data/app/com.nativebasekitchensink-2/base.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.nativebasekitchensink-2/split_lib
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void com.onesignal.OneSignalChromeTab.setup(android.content.Context, java.lang.String, java.lang.String, java.lang.String) (OneSignalChromeTab.java:46)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void com.onesignal.OneSignal$7.run() (OneSignal.java:1164)
07-18 12:09:32.745 4728-4779/com.nativebasekitchensink I/art:     at void java.lang.Thread.run() (Thread.java:761)
07-18 12:09:32.803 4728-4750/com.nativebasekitchensink D/EGL_emulation: eglMakeCurrent: 0x9d02aea0: ver 2 0 (tinfo 0x9d02e950)
07-18 12:09:32.913 4728-4728/com.nativebasekitchensink D/ReactNative: ReactInstanceManager.detachViewFromInstance()
07-18 12:09:32.922 4728-4756/com.nativebasekitchensink W/unknown:ReactNative: StatusBarModule: Ignored status bar change, current activity is null.
07-18 12:11:00.657 4728-4734/com.nativebasekitchensink I/art: Do partial code cache collection, code=30KB, data=30KB
07-18 12:11:00.657 4728-4734/com.nativebasekitchensink I/art: After code cache collection, code=30KB, data=30KB
07-18 12:11:00.657 4728-4734/com.nativebasekitchensink I/art: Increasing code cache capacity to 128KB
```

I have the same result when doing a native initialization in `build.gradle` via the old docs.

Thank you for the help so far.

**Comment by joeyscarim** [comment]
@ashokkumar88 where did you see `OneSignal.getTags()` firing? I don't see it firing anywhere and can't seem to reach it for a console log since my app crashes right away when init happens.

**Comment by OlaAlsaker** [comment]
I had the same error as you, but followed the solution found in #515 . Not it works!

**Comment by Nightsd01** [comment]
@joeyscarim I noticed that your `com.android.support:appcompat` version (23) is older than your `compileSdkVersion` (27).

Can you try replacing it with this?

```
compile "com.android.support:appcompat-v7:27.1.0"
```

Also, what is your gradle version in `gradle-wrapper.properties`?

**Comment by Nightsd01** [comment]
@joeyscarim Closing due to no response - did you get your issue fixed? If not please reply and I'll be happy to reopen and help investigate.
