### ISSUE TITLE
3.2.6 Android crash: invoking 'void com.onesignal.OneSignal$ChangeTagsUpdateHandler.onSuccess(org.json.JSONObject)' on a null object reference

### ISSUE THREAD

**Issue by sunweiyang** [OneSignal/react-native-onesignal#603]
**Description:**
In 3.2.6, I'm getting the following Android crash: `Attempt to invoke interface method 'void com.onesignal.OneSignal$ChangeTagsUpdateHandler.onSuccess(org.json.JSONObject)' on a null object reference`. I have to use 3.2.5, which doesn't result in a crash for me. The iOS version of the app seems to be working fine.

![screenshot_20180812-123954](https://user-images.githubusercontent.com/12490625/44005750-73831e9e-9e2d-11e8-84f5-f7a40802d9ad.png)

I believe it's related to me calling the following in `componentDidMount` (no crash exists when I comment these out):
```
  OneSignal.sendTag("user_id", <USERID>);
  OneSignal.sendTag("first_name",  <FIRSTNAME>);
  OneSignal.sendTag("last_name",  <LASTNAME>);
  OneSignal.sendTag("email",  <EMAIL>);
```

I use the same account to log into multiple devices during testing, in case that's relevant information.

**Environment**
I'm using RN 0.56 and Gradle 4.4, and I have reproduced this issue on Android SDK 26-28.

**Steps to Reproduce Issue:**
  1. Update to 3.2.6 via `yarn upgrade react-native-onesignal --latest`
  2. Observe this crash when OneSignal.sendTag() is called

**Anything else:**
Relevant logcat output:
```
    --------- beginning of crash
08-11 03:38:12.741 23022-23073/com.theskale.app E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.theskale.app, PID: 23022
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.onesignal.OneSignal$ChangeTagsUpdateHandler.onSuccess(org.json.JSONObject)' on a null object reference
        at com.onesignal.OneSignal$11.run(OneSignal.java:1508)
        at com.onesignal.OneSignal.sendTags(OneSignal.java:1524)
        at com.onesignal.OneSignal.sendTags(OneSignal.java:1450)
        at com.onesignal.OneSignal.sendTag(OneSignal.java:1426)
        at com.geektime.rnonesignalandroid.RNOneSignal.sendTag(RNOneSignal.java:138)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by sunweiyang** [comment]
Never mind, I didn't notice that sending tags API for this library has changed. Works when I do this:
```
OneSignal.sendTags({
    user_id: <USERID>,
    first_name: <FIRSTNAME>,
    last_name: <LASTNAME>,
    email: <EMAIL>
  });
```
