### ISSUE TITLE
Error java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by arryanggaputra** [OneSignal/react-native-onesignal#614]
**Description:**

I got this error when my app just started, but when I disabled `this.initOnesignal()` there's no error

**Environment**

Version : ^3.2.5
Using NPM, manual linking , follow onesignal documentation properly

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
2. call `this.initOnesignal()` on `componentDidMount()`
3. Error java.lang.Double cannot be cast to java.lang.String
```javascript

  componentDidMount() {
    this.initOnesignal(); 
  }

  initOnesignal() {
    OneSignal.setLogLevel(6, 0);
    OneSignal.init("cb8cbfff-d6e5-4f2b-9aff-2a91f0e868d7", {
      kOSSettingsKeyAutoPrompt: true
    });
    OneSignal.inFocusDisplaying(2);
    OneSignal.configure();
    OneSignal.addEventListener("received", this.onReceived);
    OneSignal.addEventListener("opened", this.onOpened);
    OneSignal.addEventListener("ids", this.onIds);
  }
```

**Comment by Nightsd01** [comment]
Please post the stack trace of the crash, until then I’ll close the issue. If you can post the stacktrace and some details I’ll be happy to reopen and help investigate.

**Comment by arryanggaputra** [comment]
```
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: Exception in native call
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:134)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:751)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:154)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
08-28 11:36:11.294  2812  4541 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:761)
08-28 11:36:11.333  2812  2812 D ReactNative: CatalystInstanceImpl.destroy() start
08-28 11:36:11.335  2812  2812 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
08-28 11:36:11.338  2812  4601 D ReactNative: CatalystInstanceImpl.destroy() end
08-28 11:36:11.411  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.414  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.415  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.415  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.416  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.503  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.574  2812  2812 W unknown:ReactNative: Invoking JS callback after bridge has been destroyed.
08-28 11:36:11.728  2812  2812 W unknown:ReactNative: Calling JS function after bridge has been destroyed: JSTimers.callTimers([[545]])
```

@Nightsd01  how about this?

**Comment by arryanggaputra** [comment]
@Nightsd01  okay, i got the problem, inside `this.onIds()` I call `OneSignal.sendTag()` with integer/double value, this cause an error. I think we need to add a documentation about this. `OneSignal.sendTag()` should receive a string
