### ISSUE TITLE
[Android] FAILURE: Build failed with an exception. react-native-google-analytics-bridge and react-native-onesignal not compatible

### ISSUE THREAD

**Issue by retyui** [OneSignal/react-native-onesignal#631]
**Description:**
I'm adding you module to mo project, by [instruction](https://documentation.onesignal.com/v5.0/docs/react-native-sdk-setup). After that `build` began to break down.

**Environment**
OneSignal React-Native SDK - latest version

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      CPU: x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 501.86 MB / 15.55 GB
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 8.12.0 - /usr/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
        API Levels: 23, 25, 26, 27, 28
    npmPackages:
      react: ^16.5.0 => 16.5.0 
      react-native: ^0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Steps to Reproduce Issue:**
1. `git clone https://github.com/retyui/demo-filed-build`
2.  `cd demo-filed-build ;  yarn ; cd android ; ./gradlew app:assembleDebug`

### All log output: 
https://gist.github.com/retyui/af0363d58ca9e676a63de6b6789f8eed
### Short log output: 
```js
Exception in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

```

**Comment by Nightsd01** [comment]
Hi, I tried running your demo project and was unable to fetch a certain dependency in your project?

```
npm ERR! code E403
npm ERR! 403 Forbidden: intl@^1.2.5

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bradhesse/.npm/_logs/2018-09-14T01_25_47_413Z-debug.log
```

**Comment by retyui** [comment]
@Nightsd01 
I fixed this problem. Can you try again? _Don't forget to update `master` branch_

**Comment by retyui** [comment]
@Nightsd01 Did you look at what's the problem?

**Comment by retyui** [comment]
@Nightsd01 
I decided to check because of which library the assembly project breaks. 
It turned out to be an `react-native-google-analytics-bridge`, if you exclude it from the dependent project assembly will pass without problems.
How fixed this problem?

**Comment by retyui** [comment]
# Fix: 

**android/build.gradle**
```diff
ext {
+  googlePlayServicesVersion = "12.0.1"
    compileSdkVersion = 27
    buildToolsVersion = "27.0.3"
    supportLibVersion = "26.1.0"
    minSdkVersion = 19
    targetSdkVersion = 26
}
```

**Comment by jeevankumarkanuganti** [comment]
> # Fix:
> **android/build.gradle**
> 
> ```diff
> ext {
> +  googlePlayServicesVersion = "12.0.1"
>     compileSdkVersion = 27
>     buildToolsVersion = "27.0.3"
>     supportLibVersion = "26.1.0"
>     minSdkVersion = 19
>     targetSdkVersion = 26
> }
> ```



It worked for me . Thanks
