### ISSUE TITLE
Can not build app because of different compile and runtime versions.

### ISSUE THREAD

**Issue by jahicDario** [OneSignal/react-native-onesignal#745]
**Description:**
Can not build app after installing and linking library. Getting next error: 
Android dependency 'com.google.android.gms:play-services-location' has different version for the compile (15.0.1) and runtime (16.0.0) classpath. You should manually set the same version via DependencyResolution

**Environment**
React Native Environment Info:
System:
OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Memory: 132.78 MB / 7.66 GB
Shell: 4.3.48 - /bin/bash
Binaries:
Node: 8.12.0 - /usr/local/bin/node
Yarn: 1.9.4 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
npmPackages:
react: 16.6.3 => 16.6.3
react-native: 0.57.8 => 0.57.8
npmGlobalPackages:
create-react-native-app: 2.0.2
react-native-cli: 2.0.1

**Steps to Reproduce Issue:**

1. npm install --save react-native-onesignal
2. react-native link react-native-onesignal
3. npm start
4. react -native run-android

**Files:**
android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        googlePlayServicesLocationVersion = "16.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
         maven {
           url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
           url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

android/app/build.gradle

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

apply plugin: "com.android.application"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.plt.trackpilot"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
        missingDimensionStrategy 'react-native-camera', 'mlkit' 
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-onesignal')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-fs')
    compile project(':react-native-image-base64')
    compile project(':react-native-camera')
    compile project(':react-native-signature-capture')
    compile project(':react-native-background-fetch')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-splash-screen')
    compile project(':react-native-autogrow-textinput')
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter')
    compile project(':react-native-launch-navigator')
    compile project(':react-native-device-info')
    compile project(':react-native-imei')
    compile project(':react-native-uuid-generator')
    compile project(':react-native-tts')
    compile project(':react-native-vector-icons')
    compile project(':react-native-sqlite-storage')
    compile project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-background-timer')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

```

**Comment by rgomezp** [comment]
Hello,
This issue seems unrelated to OneSignal. What makes you think this has to do with our SDK?

**Comment by mgcrea** [comment]
I'm encoutering a related issue as well. Linking onesignal does make my app crash on launch:

```
04-26 12:22:50.305  9196  9196 E AndroidRuntime: FATAL EXCEPTION: main
04-26 12:22:50.305  9196  9196 E AndroidRuntime: Process: com.jooncamobile, PID: 9196
04-26 12:22:50.305  9196  9196 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.jooncamobile-Xy1T0lUVTc3ttEVfx1RhYQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.jooncamobile-Xy1T0lUVTc3ttEVfx1RhYQ==/lib/x86, /data/app/com.jooncamobile-Xy1T0lUVTc3ttEVfx1RhYQ==/base.apk!/lib/x86, /system/lib]]
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-26 12:22:50.305  9196  9196 E AndroidRuntime: 	... 12 more
```

Googling it says it's an issue about com.google.android.gms:play-services-location version mismatch.

<img width="431" alt="Screenshot 2019-04-26 at 13 01 14" src="https://user-images.githubusercontent.com/108273/56803608-6b9b6180-6823-11e9-8824-ada6c161b92a.png">

Tried to use the gradle plugin as [specified here](https://documentation.onesignal.com/docs/react-native-sdk-setup#section-adding-the-gradle-plugin):

But encounters build errors

```
$ react-native run-android
info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'JooncaMobile'.
> Could not get unknown property 'android' for root project 'JooncaMobile' of type org.gradle.api.Project.
```

**Comment by rgomezp** [comment]
@jahicDario ,
There are two things I think you can try. First, comment out the section ` // applicationVariants are e.g. debug, release` which could be conflicting with the gradle plugin. If that doesn't work try running a clean build.

**Comment by rgomezp** [comment]
Closing due to no response
