### ISSUE TITLE
 Android project without build variants

### ISSUE THREAD

**Issue by bunyaminmrcn** [OneSignal/react-native-onesignal#802]
**Description:**

Hi . I just created new react-native project with RN 0.60 and added react-native-onesignal also configured . But error occured while compiling.

**Environment**

1. react-native-onesignal: 3.2.14
2. react-native : 0.60.3

**Steps**
1. one-signal gradle-plugin added
2. For androidX , already exist an conf in gradle.properties 
- android.useAndroidX=true
- android.enableJetifier=true

 **Issue:**
> while building project i got this error log . How fix this ? #792 did these steps.

ERROR: The module 'react-native-onesignal' is an Android project without build variants, and cannot be built.
Please fix the module's configuration in the build.gradle file and sync the project again

**Comment by draganjovanovich** [comment]
I fixed similar problem with opening whole react-native android project in android-studio,
than right-click on react-native-onesignal folder in project menu -> Refactor -> migrate to andoridx.
After that i was able to compile successifuly.

**Comment by sefatunckanat** [comment]
@bunyaminmrcn Hocam 0.6 üzerinde başarıyla çalıştırabildin mi eklentiyi? rnfirebasede baya hata aldım 0.6 için hazır değil gibi. Bunu dönmeyi planlıyorum 🤔

**Comment by bunyaminmrcn** [comment]
> @bunyaminmrcn Hocam 0.6 üzerinde başarıyla çalıştırabildin mi eklentiyi? rnfirebasede baya hata aldım 0.6 için hazır değil gibi. Bunu dönmeyi planlıyorum 🤔

Its works expected now. Check your bundle identifier, Setup onesignal app with dashboard 
And build.gradle file of react-native-onesignal edit this section,  line number 63 
`
    if (projName != 'app' && projName != 'react-native-onesignal')
        return
` 
Then clean project. No issue .

**Comment by sefatunckanat** [comment]
> > @bunyaminmrcn Hocam 0.6 üzerinde başarıyla çalıştırabildin mi eklentiyi? rnfirebasede baya hata aldım 0.6 için hazır değil gibi. Bunu dönmeyi planlıyorum 🤔
> 
> Its works expected now. Check your bundle identifier, Setup onesignal app with dashboard
> And build.gradle file of react-native-onesignal edit this section, line number 63
> `if (projName != 'app' && projName != 'react-native-onesignal') return`
> Then clean project. No issue .

i get an error on starting app.  Can you explain the installation stages on the empty project? Do I need to modify the build file as in the document? I think my plugins are breaking

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
	at android.app.ActivityThread.installProvider(ActivityThread.java:6589)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6082)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988)
	at android.app.ActivityThread.access$1200(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.localreminder-qeOKVfhVImYlrXsC1AFndQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.localreminder-qeOKVfhVImYlrXsC1AFndQ==/lib/arm64, /data/app/com.localreminder-qeOKVfhVImYlrXsC1AFndQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 12 more
 ```
