### ISSUE TITLE
Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by omars94** [OneSignal/react-native-onesignal#822]
**Description:**

I am running this app on android and currently testing on android 8.0 and 9.0 and when I receive many notifications and app is in background i get ( app name ) keeps stopping and when i debug it the error is 

**Environment**

1. react-native-onesignal 3.2.14
2. yarn

![image](https://user-images.githubusercontent.com/23584801/61875093-95cbf080-aef2-11e9-8561-f453df2ec8ee.png)

**Steps to Reproduce Issue:**

1. Install the OneSignal SDK using npm into your project
  2. Initialize the SDK in the android device 8.0 or 9.0
  3. Attempt to receive  many push notifications while app is closed or in background

**Anything else:**

(crash stacktraces, as well as any other information here)
the error i am recieving 

java.lang.RuntimeException: Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
        at android.app.ActivityThread.-wrap17(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
        at android.os.Parcel.readException(Parcel.java:2012)
        at android.os.Parcel.readException(Parcel.java:1950)
        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.onesignal.GcmBroadcastReceiver.startGCMServiceWithJobScheduler(GcmBroadcastReceiver.java:178)
        at com.onesignal.GcmBroadcastReceiver.startGCMService(GcmBroadcastReceiver.java:146)
        at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:131)
        at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:72)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
        at android.app.ActivityThread.-wrap17(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by omars94** [comment]
![image](https://user-images.githubusercontent.com/23584801/61875871-3c64c100-aef4-11e9-8acf-c6cc35652cf1.png)

**Comment by jkasten2** [comment]
@omars94 Thanks for reporting. This was recently fixed in https://github.com/OneSignal/OneSignal-Android-SDK/pull/804

Once the OneSignal native Android SDK is released a OneSignal React Native release will follow

**Comment by jkasten2** [comment]
Updated, this is now available in the OneSignal-Android-SDK 3.11.2, an update to the React Native SDK will follow later this week.

**Comment by rgomezp** [comment]
Issue has been resolved
