### ISSUE TITLE
E/OneSignal: Error Getting FCM Token

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [OneSignal/react-native-onesignal#855]
2019-09-13 14:32:28.361 14885-15462/com.XXXXXX E/OneSignal: Error Getting FCM Token
    java.io.IOException: INVALID_SENDER
        at com.google.firebase.iid.zzr.zza(Unknown Source:66)
        at com.google.firebase.iid.zzr.zza(Unknown Source:79)
        at com.google.firebase.iid.zzu.then(Unknown Source:4)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-09-13 14:32:41.504 14885-15275/com.XXXXXX E/FirebaseInstanceId: Token retrieval failed: INVALID_SENDER
2019-09-13 14:33:42.275 14885-15275/com.XXXXXX E/FirebaseInstanceId: Token retrieval failed: INVALID_SENDER
2019-09-13 14:35:43.309 14885-15275/com.XXXXXX E/FirebaseInstanceId: Token retrieval failed: INVALID_SENDER

**Comment by rgomezp** [comment]
Please follow our issue guidelines or contact our support channel at OneSignal.com
