### ISSUE TITLE
Conflict react-native-maps with react-native-onesignal (android)

### ISSUE THREAD

**Issue by abdullah-dev11** [OneSignal/react-native-onesignal#88]
Hello,

I did new installation with react native

react native onesignal is working great ... but when ever install react-native-map and call MapView component , app will get crashed

but if I use react-native-map without installing onesignal , map work fine

**Comment by avishayil** [comment]
Take a look at https://github.com/geektimecoil/react-native-onesignal/issues/2

**Comment by note89** [comment]
Any solution to this ?

**Comment by note89** [comment]
Gettings this, would really want to use OneSignal instead of SNS but its not working for me

```
10-17 18:51:40.296 25302 25302 W FlurryAgent: Error logged: uncaught
10-17 18:51:40.305 25302 25480 W FlurryAgent: Flurry session ended
10-17 18:51:40.370   683   683 I MSM-irqbalance: Decided to move IRQ137 from CPU2 to CPU3
10-17 18:51:40.421 25302 25302 E AndroidRuntime: FATAL EXCEPTION: main
10-17 18:51:40.421 25302 25302 E AndroidRuntime: Process: com.ahead_mobile.debug, PID: 25302
10-17 18:51:40.421 25302 25302 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.ahead_mobile.debug-1/base.apk)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:66)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:28)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.view.Choreographer.doFrame(Choreographer.java:603)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:152)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5497)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-17 18:51:40.421 25302 25302 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-17 18:51:40.421 25302 25302 D AppTracker: App Event: crash
10-17 18:51:40.427  1142  5594 W ActivityManager:   Force finishing activity com.ahead_mobile.debug/com.ahead_mobile.MainActivity
10-17 18:51:40.441  1142 25510 D DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@1476723100432.txt
10-17 18:51:40.468  1142  1172 W ActivityManager:  Dismiss app error dialog : com.ahead_mobile.debug
10-17 18:51:40.468  1142  1172 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=1467443035104 duration=129861 nesting=0
10-17 18:51:40.477 25302 25302 I Process : Sending signal. PID: 25302 SIG: 9
10-17 18:51:40.564  1142  4586 D GraphicsStats: Buffer count: 13
10-17 18:51:40.564  1142  5135 I WindowState: WIN DEATH: Window{6c54116 u0 com.ahead_mobile.debug/com.ahead_mobile.MainActivity}
10-17 18:51:40.564  1142  5593 I ActivityManager: Process com.ahead_mobile.debug (pid 25302) has died
10-17 18:51:40.565  1142  5593 W ActivityManager: Scheduling restart of crashed service com.ahead_mobile.debug/com.onesignal.SyncService in 1000ms
10-17 18:51:40.567  1142  1170 V ActivityManager: killProcessGroupAsync took 3 ms for PID 25302 on thread 14
10-17 18:51:40.611  5154  5154 D AppTracker: App Event: start
10-17 18:51:40.689  1142  5100 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 25302 uid 10343
10-17 18:51:40.700  5154  5154 D AbstractTracker: Event success
10-17 18:51:40.961  1142  1192 W WindowAnimator: Failed to dispatch window animation state change.
10-17 18:51:40.961  1142  1192 W WindowAnimator: android.os.DeadObjectException
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.BinderProxy.transactNative(Native Method)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.BinderProxy.transact(Binder.java:527)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:288)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:688)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at com.android.server.wm.WindowAnimator.access$000(WindowAnimator.java:54)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:125)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.view.Choreographer.doFrame(Choreographer.java:603)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.Handler.handleCallback(Handler.java:739)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.Handler.dispatchMessage(Handler.java:95)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.Looper.loop(Looper.java:152)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at android.os.HandlerThread.run(HandlerThread.java:61)
10-17 18:51:40.961  1142  1192 W WindowAnimator:    at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by note89** [comment]
When i remove oneSignal everything works.

**Comment by note89** [comment]
i added this 

```
    compile "com.google.android.gms:play-services-base:9.6.1"
    compile 'com.google.android.gms:play-services-maps:9.6.1'
```

Now i can start my app. Don't know how well it works yet thou

**Comment by avishayil** [comment]
Thanks for reporting @note89 
Please let us know if you have any more problems.

**Comment by gitsebs** [comment]
Still getting this error

@note89 May I ask where you placed the two lines?

**Comment by note89** [comment]
`android/app/build.gradle` -> `dependencies`
but now i have 
```
    compile 'com.google.android.gms:play-services-base:+'
    compile 'com.google.android.gms:play-services-maps:+'
```

**Comment by gitsebs** [comment]
@note89 Thank you! All working now.

May I ask why this fixes the problem? Not very experienced with ReactNative/Android dev
