### ISSUE TITLE
conflict with react-native-onesignal, react-native-code-push and firebase, FirebaseInstanceId: Failed to get FIS auth token

### ISSUE THREAD

**Issue by omarDtp** [OneSignal/react-native-onesignal#997]
**Description:**
my application supports remote push notification and local schedule notification therefore i installed both libraries react-native-onesignal and react-native-push-notification.
it was working fine till lately i got this error on android devices

`2020-05-27 16:51:16.628 27376-27663/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token
2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
2020-05-27 16:52:31.196 27376-27764/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token`

(your description here)

**Environment**
environment
"@react-native-firebase/app": "^7.1.0",
 "react": "16.9.0",
"react-native": "0.61.5",
    "react-native-onesignal": "^3.7.3",
    "react-native-push-notification": "^3.5.2",

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
This seems different than #983 but both are issues involving the two conflicting libraries. I'd appreciate you commenting over in the [React Native Repo issue](https://github.com/facebook/react-native/issues/26199) that is ongoing (seems more related to iOS, but still worth looking at/upvoting).

In the meantime, perhaps adding the [OneSignal gradle plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) will fix this issue for you.

Let us know if this works! Cheers

**Comment by omarDtp** [comment]
@rgomezp thanks I solved it, it was an issue with license agreement on firebase, I had to agree to new license agreement

**Comment by rgomezp** [comment]
Great to hear @omarDtp ,
Enjoy!
